### ISSUE TITLE
集成了，但是访问后台报错

### ISSUE THREAD

**Issue by yanyanpeng** [zhangdaiscott/JimuReport#10]
![image](https://user-images.githubusercontent.com/60538506/98130545-53ff6780-1ef5-11eb-874b-14d838f440b8.png)
![image](https://user-images.githubusercontent.com/60538506/98130631-6da0af00-1ef5-11eb-9ed8-1afdaf0f819a.png)
![image](https://user-images.githubusercontent.com/60538506/98130781-96c13f80-1ef5-11eb-8287-4e1221af6d1c.png)

**Comment by zhangdaiscott** [comment]
用这个类覆盖下试试
[TokenUtils.zip](https://github.com/zhangdaiscott/JimuReport/files/5491376/TokenUtils.zip)

**Comment by zhangdaiscott** [comment]
ISysBaseAPI 集成下类CommonAPI.java
[Uploading CommonAPI.zip…]()

**Comment by zhangdaiscott** [comment]
网友总结2.2集成时操作，可能对使用老版本的朋友有帮助。
1. 文档中关于CommonAPI的路径，位置org.jeecg.common.api
2. public interface ISysBaseAPI extends CommonAPI
3. SysBaseApiImpl未实现类的方法，直接移植2.3版本中的。
