### ISSUE TITLE
建议支持多租户和移动端展示

### ISSUE THREAD

**Issue by mhlywxl** [zhangdaiscott/JimuReport#100]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
？多租户和移动方案不是提供了吗

**Comment by mini2014** [comment]
已收录

**Comment by zhangdaiscott** [comment]
暂时不好实现，先归集到
https://github.com/zhangdaiscott/JimuReport/issues/138
