### ISSUE TITLE
积木报表套打问题 新

### ISSUE THREAD

**Issue by chenshan07073311** [zhangdaiscott/JimuReport#101]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/27768927/108687450-b1193a80-7531-11eb-99e2-024155af139a.png)
![image](https://user-images.githubusercontent.com/27768927/108687469-b8404880-7531-11eb-9f46-8320d9ba0883.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
已收录

**Comment by mini2014** [comment]
线上已修改，你可以再测试一下；
离线版本，会再下个版本更新；

**Comment by zhangdaiscott** [comment]
试试这个版本解决了没
```
<dependency> 
<groupId>com.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.2.0-beta</version> 
</dependency>
```
