### ISSUE TITLE
数据格式为数值，当设置小数位数后，数据格式的千分符失效

### ISSUE THREAD

**Issue by 13071652014** [zhangdaiscott/JimuReport#102]
##### 版本号：
1.1.09

##### 问题描述：
数据格式为数值，当设置小数位数后，数据格式的千分符失效

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/56342460/108812985-111fe780-75eb-11eb-9063-52f2da7b4a7b.png)
![图片](https://user-images.githubusercontent.com/56342460/108813002-17ae5f00-75eb-11eb-87fd-df7a29aa0e3e.png)
![图片](https://user-images.githubusercontent.com/56342460/108813021-21d05d80-75eb-11eb-8a35-17493b782f52.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
已收录

**Comment by zhangdaiscott** [comment]
试试这个版本解决了没
```
<dependency> 
<groupId>com.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.2.0-beta</version> 
</dependency>
```
