### ISSUE TITLE
api数据源接口返回0条数据，但是报表依旧显示初始化的数据

### ISSUE THREAD

**Issue by S1ow** [zhangdaiscott/JimuReport#104]
##### 版本号：
1.1.09

##### 问题描述：
带参数api数据源报表，初始化有两条数据，没有问题，通过参数筛选后，接口也接收到了参数，返回是0条数据，但是报表依旧展示2条数据。

##### 截图&代码：
录制个视频，可以看下吧
地址：http://qn.oneidea.xyz/meeting_01.mp4

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by S1ow** [comment]
再补充个bug吧，如果api数据初始化的是0条数据，静态的表格数据都不会渲染，并且查询栏的日期选择期，被遮挡了。
![image](https://user-images.githubusercontent.com/13724705/109479099-04046c00-7ab5-11eb-80a5-4ba236576af4.png)

**Comment by zhangdaiscott** [comment]
收录

**Comment by 1298191366** [comment]
请更新到最新版再次尝试

**Comment by S1ow** [comment]
> 请更新到最新版再次尝试

在1.2.0版本尝试，未解决。

**Comment by 1298191366** [comment]
我们这边没复现，是否可以在我们官网设计一下，并白浏览地址的id发一下

**Comment by 1298191366** [comment]
我说的是第二个bug
