### ISSUE TITLE
文档中权限控制这个文件JimuReportTokenService.java 页面404了

### ISSUE THREAD

**Issue by Misakimmmm** [zhangdaiscott/JimuReport#105]
##### 版本号：
1.1.09

##### 问题描述：
文档中权限控制这个文件JimuReportTokenService.java 页面404了

##### 截图&代码：

![image](https://user-images.githubusercontent.com/64182473/109611410-2788ee80-7b69-11eb-9f95-b321805b5b00.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Misakimmmm** [comment]
> 友情提示： 未按格式要求发帖，会直接删掉。

编辑了

**Comment by zhangdaiscott** [comment]
https://github.com/zhangdaiscott/JimuReport/blob/master/config/JimuReportTokenService.java
