### ISSUE TITLE
集成后进入页面时，后台token报空

### ISSUE THREAD

**Issue by baroknight** [zhangdaiscott/JimuReport#106]
##### 版本号：
jimuReport版本号：1.1.09
jeecgboot版本号：2.2.0
sqlserver:版本号：2012

##### 问题描述：
按照文档去集成，除了由于使用的数据库是sqlserver，并且sql语句对应的表内容都能在现有数据库中找到，没有执行该添加sql步骤外，其他步骤都完成，但是集成后，点击菜单进去，页面报错，后台显示token失效，重新登录，并且为空

##### 截图&代码：
![image](https://user-images.githubusercontent.com/52994067/109618757-e39ae700-7b72-11eb-803e-efd827c743bd.png)

![image](https://user-images.githubusercontent.com/52994067/109618817-fad9d480-7b72-11eb-872a-fbbaebad32de.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by baroknight** [comment]
已搞定，问题出在将排除拦截规则的语句放的靠后的位置，导致token依旧被拦截， 将拦截规则放文件前面一点即可

**Comment by mini2014** [comment]
好的
