### ISSUE TITLE
能否支持api导出功能

### ISSUE THREAD

**Issue by 1776340266** [zhangdaiscott/JimuReport#107]
版本号：1.1.09
问题描述：
管理场景：业务人员需要每天定时发送报表给指定客户，现在可能制作报表并通过导出功能下载excel，由业务人员手工新建邮件发送给客户
业务痛点：目前只能通过界面点击导出，需要人为干预才能达到业务要求
业务需求：希望可以提供直接按报表下载excel的api，通过api下载excel文件，这样就可以通过自定义的定时任务发送邮件给客户
截图&代码：

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
暂时不好实现，先归集到
https://github.com/zhangdaiscott/JimuReport/issues/138
