### ISSUE TITLE
离线版本设置报表参数无效

### ISSUE THREAD

**Issue by yaohuarun** [zhangdaiscott/JimuReport#109]
##### 版本号：
v1.2.1.2.0-beta

##### 问题描述：
报表sql中使用了参数，报表参数中也设置了相应的参数和初始值，预览报表时，也传了参数，但无法获取数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/25236982/110237038-9fde1e00-7f74-11eb-9ce0-253c06118f34.png)
![image](https://user-images.githubusercontent.com/25236982/110237057-aff5fd80-7f74-11eb-9330-d2490308f424.png)
![image](https://user-images.githubusercontent.com/25236982/110237089-cc923580-7f74-11eb-8268-8cc6998d6f78.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by 1298191366** [comment]
经测试无问题，你看看吧你的$放到{}外面再次尝试

**Comment by yaohuarun** [comment]
我自己书写错误导致，$要放到{}外面
