### ISSUE TITLE
菜单可以正常打开了，但是功能未展示出来，后台依旧报错

### ISSUE THREAD

**Issue by yanyanpeng** [zhangdaiscott/JimuReport#11]
![image](https://user-images.githubusercontent.com/60538506/98354111-3cda8a00-205b-11eb-981f-a1f2c8bc4b0a.png)
![image](https://user-images.githubusercontent.com/60538506/98354188-567bd180-205b-11eb-8275-86efecb25ad3.png)
![image](https://user-images.githubusercontent.com/60538506/98354226-5e3b7600-205b-11eb-8fca-749cf978a143.png)
![image](https://user-images.githubusercontent.com/60538506/98354280-6eebec00-205b-11eb-8f35-473a5b352063.png)
![image](https://user-images.githubusercontent.com/60538506/98354397-9ba00380-205b-11eb-91b1-8450e01d79ef.png)
![image](https://user-images.githubusercontent.com/60538506/98354412-a490d500-205b-11eb-96b5-91acc3244832.png)
![image](https://user-images.githubusercontent.com/60538506/98354560-d609a080-205b-11eb-89aa-0f2fc41e8ff8.png)
![image](https://user-images.githubusercontent.com/60538506/98354601-ede12480-205b-11eb-9891-84f25cd93562.png)
![image](https://user-images.githubusercontent.com/60538506/98354703-0cdfb680-205c-11eb-981c-dff6b125be0d.png)

**Comment by zhangdaiscott** [comment]
看这个文档
https://my.oschina.net/jeecg/blog/4694834
