### ISSUE TITLE
象形图选择不了图标

### ISSUE THREAD

**Issue by eyuan** [zhangdaiscott/JimuReport#111]
##### 问题描述：

想换个图标，选择后图片挂掉的状态，换了png\ico，大小也调整了30px，还是不行。。。
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
你看你的minio或者oss配置的对不对

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2186109
