### ISSUE TITLE
上传excel模板兼容性

### ISSUE THREAD

**Issue by raodeming** [zhangdaiscott/JimuReport#112]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/38421121/110267994-e1fe7280-7ffb-11eb-8395-2499f2d1b288.png)

![image](https://user-images.githubusercontent.com/38421121/110268158-2f7adf80-7ffc-11eb-9dde-1c717af2dc9b.png)

**Comment by mini2014** [comment]
下个版本就兼容了
