### ISSUE TITLE
地图无法加载数据

### ISSUE THREAD

**Issue by qsh106** [zhangdaiscott/JimuReport#113]
##### 版本号：
1.2.0 。jeecg-boot2.4

##### 问题描述：
1.地图无法加载数据，不管是SQL数据集还是api数据。
2.同时建议地图数据增加type分类，不同数据用不同颜色点表示。
##### 截图&代码：
![-3e465eda9a126d23](https://user-images.githubusercontent.com/48463491/110276816-e7dc5f80-7fcb-11eb-9087-415ef0e59a59.png)
![-4ccdd3d318bea2c5](https://user-images.githubusercontent.com/48463491/110276849-f7f43f00-7fcb-11eb-8d54-460e6c48e158.png)
![-1a9441400d4967d4](https://user-images.githubusercontent.com/48463491/110276854-f88cd580-7fcb-11eb-8ac5-06167c495205.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
经测试无问题
截图：
![image](https://user-images.githubusercontent.com/30997828/111142716-f58f7780-85bf-11eb-9eb9-d7fb81eff75e.png)
![image](https://user-images.githubusercontent.com/30997828/111142741-fc1def00-85bf-11eb-8317-199ade0f8de3.png)
可能出现的问题一：在样式-》地图设置-》地图维护未配置
                  问题二：在数据源新增和编辑之后，包括数据库保存需要刷新设计器页面，再点击运行即可
请再次尝试
