### ISSUE TITLE
希望能支持批量套打及支持相关打印成功回调接口，方便对接。

### ISSUE THREAD

**Issue by 464638524** [zhangdaiscott/JimuReport#114]
##### 问题描述：
希望能支持批量套打及支持相关打印成功回调接口，方便对接。

##### 截图&代码：
希望能支持批量套打及支持相关打印成功回调接口，方便对接。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
收录

**Comment by zhangdaiscott** [comment]
暂时不好实现，先归集到
https://github.com/zhangdaiscott/JimuReport/issues/138
