### ISSUE TITLE
页眉页脚自动带上日期，请求url 问题

### ISSUE THREAD

**Issue by JiChaoer** [zhangdaiscott/JimuReport#116]
##### 版本号：
1.2.0

##### 问题描述：
打印时，页眉页脚自动带上日期，请求url ，不知怎么去掉

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31977908/110611716-71f21700-81ca-11eb-9029-4488141787d6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
在下图操作处修改
![image](https://user-images.githubusercontent.com/74229017/110928214-959b9580-8361-11eb-92c5-31556cf80b1b.png)
