### ISSUE TITLE
副标题不能做到跟随数据集动态变化

### ISSUE THREAD

**Issue by xiaoxiwu** [zhangdaiscott/JimuReport#119]
##### 版本号：
1.2.0

##### 问题描述：

副标题不能做到跟随数据集动态变化
##### 截图&代码：

![QQ图片20210315094325](https://user-images.githubusercontent.com/4951602/111093098-01a11800-8573-11eb-9874-a3dbb17207ce.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
你这个有更详细的操作步骤吗？
你这个描述，不太清除说的是哪方面的内容

**Comment by xiaoxiwu** [comment]
我查询条件变更后，标题中的营收日期没办法改变

**Comment by zhangdaiscott** [comment]
不支持
