### ISSUE TITLE
很是期待这个产品，但是不太好操作哈 ，实现一个 实现一个收支情况关系太难搞了，也没有地方添加属性值哈

### ISSUE THREAD

**Issue by yanyanpeng** [zhangdaiscott/JimuReport#12]
![image](https://user-images.githubusercontent.com/60538506/98442405-59e88900-213f-11eb-8546-eee805ea27a9.png)
![image](https://user-images.githubusercontent.com/60538506/98442422-81d7ec80-213f-11eb-974f-89550801419c.png)

**Comment by zhangdaiscott** [comment]
请细化你的需求，我们尽快改进

**Comment by lsqGitHub716** [comment]
方便查看一下你配置的数据信息吗

**Comment by yanyanpeng** [comment]
是看那里的，无条件奉献




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/JimuReport"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 晚上7:00
收件人:&nbsp;"zhangdaiscott/JimuReport"<JimuReport@noreply.github.com&gt;;
抄送:&nbsp;"849610355"<849610355@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/JimuReport] 很是期待这个产品，但是不太好操作哈 ，实现一个 实现一个收支情况关系太难搞了，也没有地方添加属性值哈 (#12)





 
方便查看一下你配置的数据信息吗

**Comment by lsqGitHub716** [comment]
就是你sql的数据的表的信息，我参考你的也配置一下试试

**Comment by tygithub1** [comment]
多柱体的静态数据你先看一下  你这种返回的数据不对 应该是  [{name:2020-01,value:10000,type:'支出'},{name:2020-01,value:20000,type:'收入'}]
