### ISSUE TITLE
内容太多超出边界，打印时少半截的问题

### ISSUE THREAD

**Issue by JiChaoer** [zhangdaiscott/JimuReport#121]
##### 版本号：
1.2.0

##### 问题描述：
如图，当地址比较长时，就超出了单元格的边界，打印时，后半部分的内容就丢失了
请问，如何让超出的部分自动向下扩展呢？

##### 截图&代码：
![企业咚咚截图20210315153803](https://user-images.githubusercontent.com/31977908/111119112-a8ea7300-85a4-11eb-9535-9b5342e72d39.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
你可以使用“自动换行”
![image](https://user-images.githubusercontent.com/74229017/111596038-b2274a00-8807-11eb-8f21-084e247448ce.png)
