### ISSUE TITLE
升级1.2.0 后 mybatis3.1.2 兼容问题

### ISSUE THREAD

**Issue by zzn199121** [zhangdaiscott/JimuReport#122]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/38274171/111120531-69bd2180-85a6-11eb-8ff5-e938f7200160.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zzn199121** [comment]
补充 用的是jeecg-boot2.2.0 版本

**Comment by zhangdaiscott** [comment]
你升级<mybatis-plus.version>3.4.1</mybatis-plus.version>
