### ISSUE TITLE
SQL数据源报表，页面数据显示正常，导出excle，excle中无数据

### ISSUE THREAD

**Issue by FenixPJ** [zhangdaiscott/JimuReport#123]
##### 版本号：1.2.0
Jeecg-Boot版本2.2.1
基础框架：Spring Boot 2.1.3.RELEASE
持久层框架：Mybatis-plus_3.3.2

##### 截图&代码：
![页面显示数据](https://user-images.githubusercontent.com/49384861/111120760-bbfe4280-85a6-11eb-9d22-c345596f1394.jpg)
页面显示数据
![导出的excle](https://user-images.githubusercontent.com/49384861/111120790-c6204100-85a6-11eb-9a34-6f12b1fc8fdd.jpg)
导出的excle

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by FenixPJ** [comment]
![image](https://user-images.githubusercontent.com/49384861/111248817-9e33ea80-8645-11eb-9792-5b25a7cb2538.png)

**Comment by 1298191366** [comment]
你是就这个SQL导出不可以，还是所有的，因这个无法复现，我们这边没问题，故无法修改，如果不出意外的话你这个应该是#号，而不是$,$符号不会显示列表的
