### ISSUE TITLE
做的两张报表都只能显示到y列 z列及以后的不显示

### ISSUE THREAD

**Issue by distancezzzY** [zhangdaiscott/JimuReport#125]
##### 版本号：

1.2.0-beta
##### 问题描述：
做的两张报表都只能显示到y列 z列及以后的不显示

##### 截图&代码：

![image](https://user-images.githubusercontent.com/54434941/111144495-19ec5380-85c2-11eb-9c98-c9f1adb98be4.png)

![image](https://user-images.githubusercontent.com/54434941/111144338-e90c1e80-85c1-11eb-8185-d2aacb7329da.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
https://bootapi.jeecg.com/jmreport/view/56db5b64249c49729135eaa79af6abad
这是我在线的一个例子 超过了z列，不知道是版本问题还是你设计的问题，能不能提供在线的例子？
