### ISSUE TITLE
自定义打印尺寸241*140，点击打印报错

### ISSUE THREAD

**Issue by S1ow** [zhangdaiscott/JimuReport#126]
##### 问题描述：
1、后台application.yaml自定义打印尺寸241*140，见下图：
![image](https://user-images.githubusercontent.com/13724705/111242344-efd67800-8639-11eb-806c-33a061f3d0f1.png)

2、报表选择自定义的尺寸241纸，布局发生变化，设计过程无问题：
![1491615857489_ pic](https://user-images.githubusercontent.com/13724705/111242448-257b6100-863a-11eb-98d5-7fcc6f64b0ad.jpg)

3、预览该报表，并点击打印，F12调试查看控制台报错。并且页面一直处于loading状态，无法调用出打印。
![1501615857517_ pic](https://user-images.githubusercontent.com/13724705/111242511-49d73d80-863a-11eb-8de1-fdda39fac631.jpg)

4、切换系统默认的打印的尺寸，可正常打印。

##### 截图&代码：
请见上方步骤。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
引入依赖jar

<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>spring-boot-starter-jimureport</artifactId>
  <version>1.2.1</version>
</dependency>
