### ISSUE TITLE
相同字段，分组后排序顺序错误

### ISSUE THREAD

**Issue by S1ow** [zhangdaiscott/JimuReport#127]
##### 问题描述：

1、sql数据源，在jimuReport中预览排序无问题，见图：
![image](https://user-images.githubusercontent.com/13724705/111243643-65434800-863c-11eb-9311-6e108e661ca3.png)

2、设计报表，按照时间进行分组，为了效果增加一个不分组的，都是相同的字段
![1521615858716_ pic](https://user-images.githubusercontent.com/13724705/111243696-7ab87200-863c-11eb-93e0-41f50b8fe260.jpg)

3、预览报表，发现分组的字段排序方式不争取，未分组的正常，都是相同字段
![1531615858767_ pic](https://user-images.githubusercontent.com/13724705/111243747-8c9a1500-863c-11eb-807e-b1160f6f6c48.jpg)

##### 截图&代码：
请见上方步骤。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
暂时修改不了，

**Comment by zhangdaiscott** [comment]
暂时不好实现，先归集到
https://github.com/zhangdaiscott/JimuReport/issues/138
