### ISSUE TITLE
按文档步骤部署到本地后，部署成功，但不能新建，提示：登录已过期

### ISSUE THREAD

**Issue by lulusoft** [zhangdaiscott/JimuReport#13]
按文档步骤部署到本地后，部署成功，但不能新建，提示：登录已过期
环境：oracle11G,jeecg boot2.2.1
部署步骤：
第一步： 集成依赖 jar
第二步： 执行升级 sql
第三步：修改配置文件
第四步： 角色授权菜单，就可以看到报表设计菜单
第五步： shiro权限排除
第六步：ISysBaseAPI 集成下类CommonAPI.java
第七步：覆盖类TokenUtils.zip
第八步：从2.3覆盖org/jeecg/common/api/vo/Result.java

**Comment by lulusoft** [comment]
另外在设计的时候添加饼图保存后，再次编辑有的时候该饼图不能操作（删除，编辑）

**Comment by zhangdaiscott** [comment]
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>jimureport</artifactId>
  <version>1.0.2-beta</version>
</dependency>

是这个最新的依赖吗，另外2.2.1集成token传递成功了吗
