### ISSUE TITLE
oracle数据库中DATE类型字段无法显示短日期或长日期

### ISSUE THREAD

**Issue by dingning1098** [zhangdaiscott/JimuReport#130]
##### 截图&代码：
表格设计选了短日期
![图片](https://user-images.githubusercontent.com/44385709/111559623-d6fdcc00-87cb-11eb-97b9-2755eb2c6208.png)

预览后变成完整日期+时间格式
![图片](https://user-images.githubusercontent.com/44385709/111559633-dc5b1680-87cb-11eb-8339-afca8cdbb8f0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
请问你有什么特殊的操作吗，我这里没问题

**Comment by 1298191366** [comment]
![image](https://user-images.githubusercontent.com/30997828/111938522-29f5bd00-8b05-11eb-9c09-103c64a9997c.png)
这是oracle数据库
设计页面
![image](https://user-images.githubusercontent.com/30997828/111938566-3bd76000-8b05-11eb-8093-44c9e654f859.png)
预览页面
![image](https://user-images.githubusercontent.com/30997828/111938586-48f44f00-8b05-11eb-9b6a-2411c3a22377.png)

**Comment by dingning1098** [comment]
我是部署在私有服务器的，是否存在私有服务器版本低于官方版本的情况？

**Comment by dingning1098** [comment]
数据库为oracle 11g ，数据库中字段类型为Date，前台依旧无法进行转换，似乎直接作为了String处理
![图片](https://user-images.githubusercontent.com/44385709/112557501-94f60b00-8e07-11eb-9d2b-7eebeeb12484.png)
![图片](https://user-images.githubusercontent.com/44385709/112557525-a6d7ae00-8e07-11eb-91d5-0e6582384537.png)
版本为1.2.0
![图片](https://user-images.githubusercontent.com/44385709/112557582-bd7e0500-8e07-11eb-9032-e5606b50977f.png)

**Comment by dingning1098** [comment]
@1298191366

**Comment by 1298191366** [comment]
不存在版本问题，是否可以在我们报表制作一个，看看是否能重现，把id发一下

**Comment by 1298191366** [comment]
你可以用你线上的服务器数据库，看看是不是数据库格式问题，或者说你数剧库确认是data类型的吗，我们这边这个bug无法复现
