### ISSUE TITLE
大写的sql.字段名称包含or 等关键词，会转换成小写,不支持大小写敏感的数据库

### ISSUE THREAD

**Issue by qiuzhilin** [zhangdaiscott/JimuReport#132]
##### 问题描述：
sql 数据源，如果是大写的sql.字段名称包含or 等关键词，会转换成小写，对于大小写敏感的数据库处理不好。

##### 截图&代码：
SELECT SRC_PORT E FROM TEST；会变成SELECT SRC_PorT E FROM TEST；

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
请更新到最新版本看看是否已解决

**Comment by 1298191366** [comment]
请更新到最新版本看看是否已解决

**Comment by zhangdaiscott** [comment]
请升级到最新版本再测试
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.0-beta3</version>
</dependency>
```
http://report.jeecg.com/2078875
