### ISSUE TITLE
能否实现单数据集二维展开

### ISSUE THREAD

**Issue by baroknight** [zhangdaiscott/JimuReport#133]
##### 问题描述：
如图所示，从数据库中导入一个数据集，用二维码展示，但是通常只能单列显示，目前想实现的效果是但数据集二维覆盖整张打印纸，能否实现，或者是否打算开发这个功能？

##### 截图&代码：
图片地址：https://gitee.com/baro/pic/raw/master/%E6%83%B3%E8%A6%81%E5%AE%9E%E7%8E%B0%E7%9A%84%E6%95%88%E6%9E%9C.png

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
先归集到
https://github.com/zhangdaiscott/JimuReport/issues/138
