### ISSUE TITLE
可以自定义启动数据源位置吗

### ISSUE THREAD

**Issue by llmoe** [zhangdaiscott/JimuReport#134]
##### 版本号：
1.3.0 beat

##### 问题描述：
可以自定义启动的数据源吗，积木启动的数据源好像用Druid自动配置 是读取 spring. datasource下面的默认配置的，但是项目配置了多数据源。能像ureport哪样子 有个 BuildinDatasource 代码里面直接返回数据源给他用

##### 截图&代码：

<img width="1286" alt="截屏2021-03-20 09 17 53" src="https://user-images.githubusercontent.com/17946937/111854971-27586380-895d-11eb-99c1-f3619ca86a75.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
可以，不要数据源的位置，新版1.3.0-beta走的是springjdbc的数据源源

**Comment by llmoe** [comment]
额。。不好意思重新打开下，因为系统弄了多数据源自定义了数据源位置，然后整合积木后，一直像图上面哪样子一直Init DruidDataSourec ，我必须按照默认 spring. datasource 配置才行

**Comment by llmoe** [comment]
> 可以，不要数据源的位置，新版1.3.0-beta走的是springjdbc的数据源源

额。。不好意思重新打开下，因为系统弄了多数据源自定义了数据源位置，然后整合积木后，一直像图上面哪样子一直Init DruidDataSourec ，我必须按照默认 spring. datasource 配置才行
