### ISSUE TITLE
设置循环块后无法取消删除！

### ISSUE THREAD

**Issue by llmoe** [zhangdaiscott/JimuReport#135]
##### 版本号：
1.3.0

##### 问题描述：
设置循环块，设置错误了，但是没法取消。。什么删除行，取消数据，循环块设定取消都试了下，都删不了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/17946937/111856084-57a30080-8963-11eb-968e-3c50b661a6a6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by alanqwy** [comment]
同样的问题...废了一张报表...
