### ISSUE TITLE
表格小数点数值为0,设置显示位数无效

### ISSUE THREAD

**Issue by llmoe** [zhangdaiscott/JimuReport#136]
##### 版本号：
1.3.0

##### 问题描述：

表格小数点数值为0,设置显示位数无效，另外想请问下可以自定义设置分页的数量吗，现在是默认10个每页
##### 截图&代码：

![image](https://user-images.githubusercontent.com/17946937/111856561-81115b80-8966-11eb-84da-ff5d902ee515.png)
![image](https://user-images.githubusercontent.com/17946937/111856571-97b7b280-8966-11eb-98af-81f2fef37e27.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
收录

**Comment by tygithub1** [comment]
最新的实现是： 数字为0，不管小数位数显示0
