### ISSUE TITLE
必看常见问题

### ISSUE THREAD

**Issue by zhangdaiscott** [zhangdaiscott/JimuReport#137]
1、官方网站
http://jimureport.com
2、必看常见问题（汇总了从环境搭建入门到开发中 会遇到的各种问题）
http://report.jeecg.com/2087464
3、在线文档
http://report.jeecg.com
4. 入门教程视频
http://jimureport.com/doc/video
5. 反馈问题请发issue
https://github.com/zhangdaiscott/jimureport/issues/new

**Comment by pphanwang** [comment]
感觉做的有的拉胯，很多使用文档都没有，就readme  里面几条。本地
按照安装后页面一直加载不出。网络上的使用教程也很少。不推荐

**Comment by lijida** [comment]
代码运行404啊
![image](https://user-images.githubusercontent.com/11564543/178400781-378e77cd-cc53-4c18-8a11-8d8b81442ebf.png)
