### ISSUE TITLE
jimureport-demo 图表设计 插入图片不显示

### ISSUE THREAD

**Issue by wanghaisen** [zhangdaiscott/JimuReport#139]
##### 版本号：
1.3.0-beta

##### 问题描述：
jimureport-demo 图表设计 插入图片不显示

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26294267/112283777-7686f700-8cc3-11eb-83cf-62fd2069396b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2186109
