### ISSUE TITLE
我在使用时候发现两个问题

### ISSUE THREAD

**Issue by kukudehshuai** [zhangdaiscott/JimuReport#14]
问题1：在使用sql数据聚合的时候 ，生成分页列表   开始默认 10条/每页    第一次 点击下一页  可用   第二次点击下一页不可用
问题2：选择 图表柱状图  sql数据集   我配置的另一个数据源，不是jeecg-boot ， 然后在配置柱状图数据项绑定的时候  点击运行，后台报错，显示找的是jeecg-boot的数据源，而不是我配置的数据源

**Comment by kukudehshuai** [comment]
![image](https://user-images.githubusercontent.com/73113771/98624724-56c0e900-2349-11eb-8bc3-c3edfae6c515.png)
问题一图片

**Comment by kukudehshuai** [comment]
![image](https://user-images.githubusercontent.com/73113771/98625102-00a07580-234a-11eb-8a9b-0d85a5c30c5b.png)
问题二图片

**Comment by mini2014** [comment]
一、看看你的代码是不是最新版本的

二、如果已经是最新版本的，点击“保存”按钮，重新保存一下；

三、分页的那个，看看添加sql的时候，有没有勾选上“分页”

**Comment by kukudehshuai** [comment]
> <dependency>
>   <groupId>org.jeecgframework.boot</groupId>
>   <artifactId>jimureport</artifactId>
>   <version>1.0.2-beta</version>
> </dependency>



> 一、看看你的依赖最新版本的
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework.boot</groupId>
>   <artifactId>jimureport</artifactId>
>   <version>1.0.2-beta</version>
> </dependency>
> ```
> 
> 二、如果已经是最新版本的，点击“保存”按钮，重新保存一下；
> 
> 三、分页的那个，看看添加sql的时候，有没有勾选上“分页”

是最新版本，以及勾选上分页了   情况是 第一次点击下一页生效，然后再一次点击下一页就没反应了

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
