### ISSUE TITLE
积木报表如果使用自定义的数据源

### ISSUE THREAD

**Issue by JiChaoer** [zhangdaiscott/JimuReport#140]
##### 版本号：
1.2.0

##### 问题描述：

积木报表如果使用自定义的数据源呢？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/31977908/112291602-375ca400-8ccb-11eb-83e8-ab5bb4aadcc7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by llmoe** [comment]
同样问题。。因为系统弄了多数据源自定义了数据源位置，然后整合积木后，启动就一直 Init DruidDataSourec ，我必须按照默认 spring. datasource 配置才行

**Comment by zhangdaiscott** [comment]
请升级到最新版本再测试
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.0-beta3</version>
</dependency>
```
http://report.jeecg.com/2078875

**Comment by zhangdaiscott** [comment]
最新版本积木报表，采用的是minidao，minidao底层引用的是springjdbc，所以只要你集成的springjdbc是自定义的数据源，积木报表就会随着你的设置走
