### ISSUE TITLE
是否有计划支持堆叠面积图？

### ISSUE THREAD

**Issue by bingle2000** [zhangdaiscott/JimuReport#141]
##### 版本号：
2.4.2

##### 问题描述：
无法展示堆叠面积图，是否计划支持echarts 或 AntV的堆叠面积图？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50697972/112449349-3e98b600-8d8e-11eb-8280-0eb7595d22e0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
先归集到
https://github.com/zhangdaiscott/JimuReport/issues/138
