### ISSUE TITLE
集成报错

### ISSUE THREAD

**Issue by cmkcmk181** [zhangdaiscott/JimuReport#142]
##### 版本号：
1.3.0-beta2

##### 问题描述：
启动时报错，已配置@SpringBootApplication(scanBasePackages ={"org.jeecg.modules.jmreport"})

##### 截图&代码：
报错信息如下：
Description:

Field reportDbDao in org.jeecg.modules.jmreport.desreport.service.a.d required a bean of type 'org.jeecg.modules.jmreport.desreport.dao.JimuReportDbDao' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

**Comment by zhangdaiscott** [comment]
请升级到最新版本再测试
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.0-beta3</version>
</dependency>
```
http://report.jeecg.com/2078875
