### ISSUE TITLE
拖动字段到列表上，预览页面异常

### ISSUE THREAD

**Issue by 17134934** [zhangdaiscott/JimuReport#148]
##### 版本号：
V1.2.0

##### 问题描述：
拖动字段到列表中，有时列表会不显示拖动的值，再正常拖动字段后预览，页面显示异常

##### 截图&代码：
![image](https://user-images.githubusercontent.com/81405104/112593932-2767d000-8e43-11eb-9d89-2bc1c9f1ab54.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
能录个重现视频吗
