### ISSUE TITLE
离线版本本地上传图片无法显示

### ISSUE THREAD

**Issue by sun153286592** [zhangdaiscott/JimuReport#149]
##### 版本号：
离线版

##### 问题描述：
离线版本，本地上传背景图片无法显示，打印时可以显示

##### 截图&代码：
报404
![image](https://user-images.githubusercontent.com/51595409/112597759-85e37d00-8e48-11eb-88cb-9475775163af.png)
实际图片存在，打印时可以调用到
![image](https://user-images.githubusercontent.com/51595409/112597874-b75c4880-8e48-11eb-8459-ec2c232d1983.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用的是local上传模式吗

**Comment by sun153286592** [comment]
> 用的是local上传模式吗

是的，本地上传

**Comment by tygithub1** [comment]
微服务?

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
