### ISSUE TITLE
新建弹窗登陆过期 预览报字段错误

### ISSUE THREAD

**Issue by loobby** [zhangdaiscott/JimuReport#15]
按文档步骤部署到本地后，部署成功，但不能新建，提示：登录已过期，可以对示例进行设计，但不能预览 提示字段错误，
环境：oracle11G,jeecg boot2.3
集成依赖 jar
执行升级 sql sql是从mysql同步过来的 
修改配置文件
角色授权菜单，就可以看到报表设计菜单
 shiro权限排除

不能新建的我进行了Debug 发现在a.class    @PostMapping({"/save"})
    public Result<?> a(HttpServletRequest var1, @RequestBody JSONObject var2) {}的这个方法中的
JimuReport var7 = (JimuReport)this.jmReportDesignService.getOne(var6);这条语句 如果是mysql的话就没有问题  oracle直接走catch

**Comment by loobby** [comment]
预览的话 只能预览测试图表和几个其他的大部分报错如下  Could not set parameters for mapping: ParameterMapping{property='id', mode=IN, javaType=class java.lang.String, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111

**Comment by zhangdaiscott** [comment]
oracle兼容性改了，升级下版本到最新
http://jimureport.com/doc/log
