### ISSUE TITLE
如何实现在代码里面导出报表的html代码

### ISSUE THREAD

**Issue by llmoe** [zhangdaiscott/JimuReport#150]
##### 版本号：
1.3.0

##### 问题描述：
可以在代码里面导出打印报表的html代码吗，或者有没有什么接口可以获取到

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
啥意思？

**Comment by llmoe** [comment]
> 啥意思？

我意思是现在有没有接口可以调用就直接获取到打印模板的pdf,或者是打印模板的html

**Comment by zhangdaiscott** [comment]
正在规划pdf，等等吧
