### ISSUE TITLE
设置背景图片不成功

### ISSUE THREAD

**Issue by he-tai** [zhangdaiscott/JimuReport#151]
##### 版本号：
V1.2.0

##### 问题描述：
1.报表设置页面，右键背景图设置
2.上传图片
3.页面没有显示上传后的页面

##### 截图&代码：
![image](https://user-images.githubusercontent.com/81545399/112784265-c549dd80-9083-11eb-9cf6-8667aaf049db.png)
![image](https://user-images.githubusercontent.com/81545399/112784292-dc88cb00-9083-11eb-9c59-4b9bf950b5ef.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用的是什么上传模式

**Comment by zhangdaiscott** [comment]
已解决，下个版本发布
