### ISSUE TITLE
设置excel公式，预览或者导出时显示值不对，有时显示值，有时不显示值

### ISSUE THREAD

**Issue by he-tai** [zhangdaiscott/JimuReport#153]
##### 版本号：
V1.2.0

##### 问题描述：
设置excel公式，预览时显示值不对

##### 截图&代码：
![image](https://user-images.githubusercontent.com/81545399/112786167-3a1f1680-9088-11eb-95ae-c0a1ec58d024.png)
![image](https://user-images.githubusercontent.com/81545399/112786178-41462480-9088-11eb-81f2-f2ac59a5404d.png)
![image](https://user-images.githubusercontent.com/81545399/112786191-486d3280-9088-11eb-964e-7fd84ec1c3d5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
待分析

**Comment by 1298191366** [comment]
请问你是什么数据库，更新到最新版本1.3.1-beta3尝试
```
        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>spring-boot-starter-jimureport</artifactId>
            <version>1.3.1-beta3</version>
        </dependency>
```
