### ISSUE TITLE
上传excel后，不选择数据集，导出页面一直在加载

### ISSUE THREAD

**Issue by he-tai** [zhangdaiscott/JimuReport#154]
##### 版本号：
1.2.0

##### 问题描述：
1.上传excel，只含有表头信息
2.直接点保存，不选择数据源信息
3.点预览按钮后，
4.点导出excel，页面一致在加载

##### 截图&代码：
上传excel后：
![image](https://user-images.githubusercontent.com/81545399/112792391-f03d2d00-9095-11eb-834f-bd8b49dea12d.png)
导出效果：
![image](https://user-images.githubusercontent.com/81545399/112792651-778aa080-9096-11eb-875b-6decb0d23a9d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
请将你的JOSN串粘贴一下，或者线上是否可以造一个数据，然后前后台是否报错，请详细描述
![image](https://user-images.githubusercontent.com/30997828/112924741-44eab180-9143-11eb-9539-426ab4d9c280.png)
我这个就是直接导入没有选择数据源可以导出

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
请更新到最新版本尝试，注意要配置私服
```
<dependency> 
<groupId>org.jeecgframework.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.3.2-beta</version> 
</dependency>
```
