### ISSUE TITLE
分组单元格进行合并后，预览报错

### ISSUE THREAD

**Issue by he-tai** [zhangdaiscott/JimuReport#155]
##### 版本号：
1.2.0

##### 问题描述：
分组单元格进行合并后，预览报错

##### 截图&代码：
单元格合并前：
![image](https://user-images.githubusercontent.com/81545399/112793828-8c683380-9098-11eb-8d90-0bb2137f32f1.png)
合并后：
![image](https://user-images.githubusercontent.com/81545399/112793858-968a3200-9098-11eb-8123-86b7c39139f5.png)
预览：
![image](https://user-images.githubusercontent.com/81545399/112793886-a4d84e00-9098-11eb-9814-cb2167924e9c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
目测是数据问题，对比下官方示例返回的数据格式

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by tygithub1** [comment]
新版已无此问题，请用新版测试
