### ISSUE TITLE
导出excel或pdf只能导出第一页

### ISSUE THREAD

**Issue by xiaoxiwu** [zhangdaiscott/JimuReport#157]
##### 版本号：

1.2
##### 问题描述：

导出excel或pdf只能导出第一页，无法实现全部导出或当前页导出，参数中的pageNo一直等于1 
##### 截图&代码：

![QQ图片20210330114529](https://user-images.githubusercontent.com/4951602/112930789-82543c80-914d-11eb-94d6-699d810ceef8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
当导出excel和pdf的时候会给你回传一个printAll属性，你可以判断一下，当前导出excel只有导出全部
![image](https://user-images.githubusercontent.com/30997828/113703507-806e1880-970d-11eb-933f-0224915931b8.png)

**Comment by tygithub1** [comment]
上述描述完全正确，后续版本会更新此功能，如果分页查询，返回值需要传给报表一个总数count参数，然后打印全部的时候，pageNo取1，pageSize取之前传入的count，这样就会查询所有数据了。

**Comment by zhangdaiscott** [comment]
升级到
最新版本JAR(注意配置jeecg私服)
```
<dependency> 
<groupId>org.jeecgframework.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.3.2-beta</version> 
</dependency>
```
