### ISSUE TITLE
导入excel，格式丢失

### ISSUE THREAD

**Issue by 327225487** [zhangdaiscott/JimuReport#159]
##### 版本号：
V1.2.0

##### 问题描述：
在积木里导出excel，再将导出的excel进行导入，合并单元格样式丢失

##### 截图&代码：
导出excel格式：
![image](https://user-images.githubusercontent.com/40779950/112971620-fe687780-9181-11eb-8492-d7addd3d5f3a.png)

导入excel后：
![image](https://user-images.githubusercontent.com/40779950/112971688-0d4f2a00-9182-11eb-8463-5a10e1b8fb36.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级版本
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.1-beta2</version>
</dependency>
```
