### ISSUE TITLE
添加超链接设置，链接目标选择“sales_option”，当参数设置两个参数全部勾选后，再取消其中一个，删除按钮消失，无法进行删除操作

### ISSUE THREAD

**Issue by 327225487** [zhangdaiscott/JimuReport#160]
##### 版本号：
1.2.0

##### 问题描述：
1.选择报表，添加超链接设置，链接目标选择“sales_option”
2【参数设置】参数设置两个参数全部勾选后，再取消其中一个
删除按钮消失，无法进行删除操作， 期望保留删除按钮

##### 截图&代码：

![image](https://user-images.githubusercontent.com/40779950/112972202-96666100-9182-11eb-876b-19bd98658a94.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
新版本已修复，请更新到最新版本尝试
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.1-beta2</version>
</dependency>
