### ISSUE TITLE
更改链接的链接目标后，参数设置没有更新，一直显示第一次配置的数值

### ISSUE THREAD

**Issue by 327225487** [zhangdaiscott/JimuReport#161]
##### 版本号：
1.2.0

##### 问题描述：
1.打开一个已配置链接的报表
2.更改链接的链接目标
参数设置没有更新，一直显示第一次配置的数值

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40779950/112972522-eb09dc00-9182-11eb-87ad-b2d3735dfaa1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 1298191366** [comment]
已修复，待新版本发布
