### ISSUE TITLE
当有两个以上SQL变量数据时，最后一个变量后面会产生空白行

### ISSUE THREAD

**Issue by 13071652014** [zhangdaiscott/JimuReport#162]
##### 版本号：
1.2.0

##### 问题描述：
当有两个以上SQL变量数据时，最后一个变量后面会产生空白行

##### 截图&代码：
![1](https://user-images.githubusercontent.com/56342460/113080522-a5442680-9209-11eb-93de-9ec1051d35b0.jpg)
![2](https://user-images.githubusercontent.com/56342460/113080535-a9704400-9209-11eb-806d-a124764287bb.jpg)
![3](https://user-images.githubusercontent.com/56342460/113080545-ac6b3480-9209-11eb-8edd-1f14c3dd56d8.jpg)
![4](https://user-images.githubusercontent.com/56342460/113080838-200d4180-920a-11eb-92a8-e3235a0c9400.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
如果你的数据集只有一条数据，需要按word风格自定义排版，设计报表数据集的时候是否列表设置否，如果是列表即标识有多条数据，那么多条数据只能横向设置表达式，不支持自定义排版
