### ISSUE TITLE
MiniDaoHandler类报错

### ISSUE THREAD

**Issue by cmkcmk181** [zhangdaiscott/JimuReport#164]
##### 版本号：
1.3.0-beta3

##### 问题描述：
打开主界面报错，如下：
![360截图184307089410196](https://user-images.githubusercontent.com/8915324/113244506-b6636500-92e7-11eb-90b3-638c04560531.png)
发现MiniDaoHandler类中this.namedParameterJdbcTemplate为null
不知哪里没配好？
yml配置：
minidao :
  base-package: org.jeecg.modules.jmreport.desreport.dao*
  db-type: mysql
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
项目里面集成了springjdbc了吗

**Comment by zhangdaiscott** [comment]
请尽快回复，无回复就关闭了

**Comment by fengqianliuli** [comment]
同样的问题，己集成spring-boot-jdbc-starter2.3.3
jeecgboot 2.1.4 积木1.3.1-beta
还是无法注入namedParameterJdbcTemplate和JdbcTemplate
![Uploading image.png…]()

**Comment by zhangdaiscott** [comment]
是springboot项目吗

**Comment by fengqianliuli** [comment]
> 是springboot项目吗

是的

**Comment by zhangdaiscott** [comment]
哪就奇怪了，可以把你的项目打包发出来，我们调试看看

**Comment by fengqianliuli** [comment]
代码不方便发送，可以远程调试吗

**Comment by zhangdaiscott** [comment]
你单独集成minidao试试，远程不了

**Comment by fengqianliuli** [comment]
单独集成minidao我怎么测试是否可以jdbctemplate注入成功呢

**Comment by fengqianliuli** [comment]
我看你们文档里需要配置minidao的包路径，但是现在我这个包是个空包，是这个原因吗
![image](https://user-images.githubusercontent.com/63761208/113973595-25543700-986f-11eb-82e8-7e5f861feeb4.png)
![image](https://user-images.githubusercontent.com/63761208/113973594-25543700-986f-11eb-918d-1bae3a1aeffd.png)

**Comment by fengqianliuli** [comment]
我看你们文档里需要配置minidao的包路径，但是现在我这个包是个空包，是这个原因吗
![image](https://user-images.githubusercontent.com/63761208/113973595-25543700-986f-11eb-82e8-7e5f861feeb4.png)
![image](https://user-images.githubusercontent.com/63761208/113973594-25543700-986f-11eb-918d-1bae3a1aeffd.png)

**Comment by fengqianliuli** [comment]
测试了单独集成minidao，报配置类初始化失败
error creating bean with name 'minidaobeanscannerconfigurer' defined in class path resource

**Comment by zhangdaiscott** [comment]
帖详细错误
自己多看看吧这个肯定有什么特殊的

**Comment by zhangdaiscott** [comment]
类似问题
https://github.com/zhangdaiscott/JimuReport/issues/170
