### ISSUE TITLE
关于token权限验证方式

### ISSUE THREAD

**Issue by JuneAll-7** [zhangdaiscott/JimuReport#165]
##### 版本号：
1.3.1 bate

##### 问题描述：
官网的token权限验证方式 是 固定token字符串进行请求头验证的，能否使进行配置 使请求头字符串进行改变，要不然 security 默认的请求头 不适配 报表工具

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.1-beta2</version>
</dependency>
```

新版支持自定义header

实现JmReportTokenServiceI的customApiHeader方法

**Comment by zhangxinyuan1** [comment]
说句实话，官网解释的token 真的很槽糕，根本没描述清楚，全靠自行理解和猜测
customApiHeader方法 只适合API数据源 + 预览模式  才进入我想问 目的是验证预览的安全吗？
getToken 方法的作用是什么？根据官网描述返回值自动设置到了 X-Access-Token ？？
getUsername(String token) 此方法是根据token获取当前用户吗？做数据隔离使用，那token跟用户就存在关系了，但设计器新建和自动保存跟预览是走不同的方法，token 在这里的意义是什么？分两块来设计呢？如何跟系统用户互通？
