### ISSUE TITLE
职员工牌打印需求

### ISSUE THREAD

**Issue by iGuozy** [zhangdaiscott/JimuReport#167]
##### 版本号：
1.2.1

##### 问题描述：
A4纸一页打印八个职员的工牌需求能否实现？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by llmoe** [comment]
同问，怎么设置一行2个 多种指定数量

**Comment by zhangdaiscott** [comment]
通过循环实现。
暂不支持一行2个

**Comment by iGuozy** [comment]
一行2个的功能，近期有没有计划增加？

**Comment by mini2014** [comment]
暂时不好实现，先归集到
#138
