### ISSUE TITLE
是否可以打印页面大小可以后台动态设置

### ISSUE THREAD

**Issue by llmoe** [zhangdaiscott/JimuReport#168]
- [x] ##### 版本号：
1.3.1

##### 问题描述：
希望打印页面大小可以后台动态设置，现在是配置是在配置文件新增，感觉很不方便

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前只支持属性配置，太灵活也不好
http://report.jeecg.com/2084081
