### ISSUE TITLE
[BUG] 导入的模板无法设置任何属性,都报错

### ISSUE THREAD

**Issue by llmoe** [zhangdaiscott/JimuReport#169]
##### 版本号：
1.3.1

##### 问题描述：
使用导入的版本的时候。。没法设置工具栏上面那些属性。什么边框，颜色字体，看控制台有js报错，模板如下附件

##### 截图&代码：

<img width="1440" alt="截屏2021-04-04 12 36 09" src="https://user-images.githubusercontent.com/17946937/113498742-587e8980-9542-11eb-827e-a7f75e190c89.png">

模板：
[xxx.xlsx](https://github.com/zhangdaiscott/JimuReport/files/6253996/xxx.xlsx)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by llmoe** [comment]
导入模板
[xxx.xlsx](https://github.com/zhangdaiscott/JimuReport/files/6253995/xxx.xlsx)

**Comment by 1298191366** [comment]
![image](https://user-images.githubusercontent.com/30997828/114365010-94ea5f00-9bac-11eb-8cea-5426fc763c53.png)
请升级到版本1.3.1-beta3即可解决
```
        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>spring-boot-starter-jimureport</artifactId>
            <version>1.3.1-beta3</version>
        </dependency>
```
