### ISSUE TITLE
查询报表控制针

### ISSUE THREAD

**Issue by jackMk** [zhangdaiscott/JimuReport#170]
##### 版本号：
1.3.1-beta

##### 问题描述：
查询报表时空指针异常，发现是jdbctemple没有被实例化，引入了springboot-jdbc-starter,

##### 截图&代码：
![image](https://user-images.githubusercontent.com/9675749/113551772-c5b81a80-9627-11eb-8de1-02d66f9d3698.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
哪你确认下springboot-jdbc-starter为什么没集成成功

**Comment by cmkcmk181** [comment]
同样问题，发现这个类所有的注入都是null，和jdbctemple应该没有关系

**Comment by zhangdaiscott** [comment]
把动态数据源的配置关闭就好了
![image](https://user-images.githubusercontent.com/3162115/115954936-45018580-a526-11eb-894c-4ec1857575bf.png)

**Comment by huangcong92** [comment]
关闭了动态数据源之后,还会一样会有这个问题

**Comment by zhangdaiscott** [comment]
哪请说明你的架构技术栈

**Comment by zhangdaiscott** [comment]
minidao集成失败，是因为开启了多数据源导致的！
方案一： 是关闭多数据源

方案二： 需要多数据源，则请按照下面步骤操作

1、minidao升级到1.7.6
2、重写starter中的注册类 MinidaoAutoConfiguration
   按照自己的规则，注入setJdbcTemplate\setNamedParameterJdbcTemplate
```
/**TODO 集成失败
* 遇到空指针 MiniDaoHandler.getReturnMinidaoResult(MiniDaoHandler.java:356)，则是因为开启了多数据源，
* 需要重写这个类，手工注入JdbcTemplate
*/
//miniDaoBeanScannerConfigurer.setJdbcTemplate();
//miniDaoBeanScannerConfigurer.setNamedParameterJdbcTemplate();
```
[Uploading MinidaoAutoConfiguration.zip…]()

**Comment by zhangdaiscott** [comment]
把动态数据源的配置关闭就好了
![image](https://user-images.githubusercontent.com/3162115/115954936-45018580-a526-11eb-894c-4ec1857575bf.png)

**Comment by zhangdaiscott** [comment]
终极解决方案，升级积木报表到最新版
解决问题：
1、解决springboot2.5集成空指针问题
2、支持动态数据源配置（minidao默认数据源名：minidaoDataSource，如果不配置则随机走第一个数据源配置）

```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.5-beta</version>
</dependency>
```

1.3.4升级1.3.5的升级SQL

```
ALTER TABLE `jimu_report_db_param`
ADD COLUMN `search_flag` int(1) NULL COMMENT '查询标识0否1是 默认0' AFTER `update_time`;
update jimu_report_db_param set search_flag = 0;
```
