### ISSUE TITLE
sql数据集是用参数进行解析where截取问题

### ISSUE THREAD

**Issue by BestClever** [zhangdaiscott/JimuReport#171]
spring-boot-starter-jimureport  1.3.0-beta3

使用sql数据集进行参数传递配置时候，报表sql如果写一个where数据预览报sql错误，大概意思是缺少了where关键字，配置两个则没问题。
配置一个where：
![image](https://user-images.githubusercontent.com/29082880/113646744-0792a080-96bc-11eb-97fd-bdaee3ead0fc.png)
配置两个where：
![image](https://user-images.githubusercontent.com/29082880/113646807-24c76f00-96bc-11eb-8eba-ee55b35e916f.png)

但是如果配置两个where，再使用的时候确是解析不出来数据

**Comment by tygithub1** [comment]
尝试用下个版本试试吧

**Comment by BestClever** [comment]
> 尝试用下个版本试试吧
