### ISSUE TITLE
数据报表背景图片上传成功，但是显示的url路径有问题

### ISSUE THREAD

**Issue by yangjunzhou861012** [zhangdaiscott/JimuReport#172]
##### 问题描述：
报表设计器-->数据报表-->新建报表-->进入数据报表设计器，然后右键，点击背景图设置-->右侧，点击背景图设置，上传-->选择图片

ps:图形报表，和打印报表中，同样存在此问题
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18575974/113652502-7a087e00-96c6-11eb-8afe-88c3a732bb91.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已解决，下个版本发布
