### ISSUE TITLE
升级1.3.1 -beta2后报错

### ISSUE THREAD

**Issue by iGuozy** [zhangdaiscott/JimuReport#176]
##### 版本号：
1.3.1 -beta2

##### 问题描述：
打开在线设计器会报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48822119/114004390-3150f080-9891-11eb-82ec-69b37e39aa02.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by iGuozy** [comment]
降回1.2.1版本 就正常。

**Comment by zhangdaiscott** [comment]
访问列表就报错吗

**Comment by zhangdaiscott** [comment]
把minidao升级到1.7.3版本，就兼容SqlServer了
```
 <!-- minidao -->
        <dependency>
            <groupId>org.jeecgframework</groupId>
            <artifactId>minidao-spring-boot-starter</artifactId>
            <version>1.7.3</version>
        </dependency>

```
