### ISSUE TITLE
自定义api 问题

### ISSUE THREAD

**Issue by lcc-java** [zhangdaiscott/JimuReport#177]
##### 版本号：
1.3.1-beta3
##### 问题描述：
测试api 数据集 ，点击api 解释 并没有如愿 进入 我的controller 

##### 截图&代码：
![image](https://user-images.githubusercontent.com/53068551/114007626-17fd7380-9894-11eb-88a1-012bde3309e5.png)
我的代码
![image](https://user-images.githubusercontent.com/53068551/114007745-2ba8da00-9894-11eb-87d8-4c8b278ef1f8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
后台有错没
F12再看看js有错没有

**Comment by lcc-java** [comment]
前后台 没发现报错
![image](https://user-images.githubusercontent.com/53068551/114117716-e202d280-9919-11eb-80dc-1b0adf24e264.png)
![image](https://user-images.githubusercontent.com/53068551/114117738-eb8c3a80-9919-11eb-82b6-b12eb26c98ae.png)

**Comment by 1298191366** [comment]
jar集成进去，测试无问题，接口可以访问，并能解析，请确认路径是否正确，如果有token是否进行了传递，没有是否被进行了拦截
![image](https://user-images.githubusercontent.com/30997828/114363285-d37f1a00-9baa-11eb-8de0-abc50525c938.png)
![image](https://user-images.githubusercontent.com/30997828/114363441-fa3d5080-9baa-11eb-98cc-d0f4061f85e0.png)

**Comment by zhangdaiscott** [comment]
已经发现问题，正在修复

**Comment by zhangdaiscott** [comment]
已经修复，升级到这个版本
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>spring-boot-starter-jimureport</artifactId>
  <version>1.3.1-beta4</version>
</dependency>
```

**Comment by lcc-java** [comment]
好的 ，谢谢
