### ISSUE TITLE
view页面获取token行为与官网描述不符合

### ISSUE THREAD

**Issue by RadianceL** [zhangdaiscott/JimuReport#178]
##### 版本号：
spring-boot-starter-jimureport-1.3.1-beta2.jar

##### 问题描述：
使用token鉴权，当业务直接跳转view（view.ftl）页面时，token没有刷新（我们业务30分钟token失效），查看源码发现，list（list.ftl）页面会优先使用url中的token覆盖localStorage，而view页面直接从localStorage中获取token没有更新覆盖行为，与官网文档中描述的行为不符，我认为是个bug，该问题出现在多个版本中，期望修复

##### 截图&代码：
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/25889174/114116523-71f34d00-9917-11eb-8a3c-5796ca2dd23f.png">

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/25889174/114116574-82a3c300-9917-11eb-8da8-d062d754cc65.png">

##### 当前解决方案
尝试采用fream的形式嵌套页面，尝试定时器覆盖localStorage中的token，如果无效，将使用nginx包一层，使其同域，定时器修改，我们认为这是一个bug，期望能在近期版本修复

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级到1.3.1-beta3

**Comment by zhangdaiscott** [comment]
参考这个
https://github.com/zhangdaiscott/jeecg-boot/issues/2405

**Comment by 495944195** [comment]
出现了同样的问题   我在8080端口的项目里面写了个html  每次跳进来 维护localStorage中的token 在跳转到当前页面

**Comment by zhangdaiscott** [comment]
已经解决了升级到最新版本
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.1-beta4</version>
</dependency>
```
