### ISSUE TITLE
SQl数据集子查询不支持where条件过滤

### ISSUE THREAD

**Issue by laijiao** [zhangdaiscott/JimuReport#18]
![image](https://user-images.githubusercontent.com/74350205/98919036-540cf200-2509-11eb-9f34-e3735351d19c.png)

**Comment by zhangdaiscott** [comment]
请把错误也贴出来

**Comment by laijiao** [comment]
![image](https://user-images.githubusercontent.com/74350205/99025835-b9fa8780-25a4-11eb-9d48-c949f6f31865.png)

报错：
{"success":false,"message":"操作失败，StatementCallback; bad SQL grammar [select * from (select xqmc,njdm,bjmc,a.xh,a.xm,if(py is null,'未提交','已提交') as zt,py,cx,txr\n from( select xqmc,xqdm,c.njdm,bjmc,xh,xm from jx_semester sm,xs_student sd\nLEFT JOIN jx_class c on c.bh=sd.bh\n) jeecg_rp_temp  where 1=1]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4","code":500,"result":null,"timestamp":1605238791577}

**Comment by tygithub1** [comment]
新建一张测试表test_rp  数据如下：
![image](https://user-images.githubusercontent.com/27989856/99790563-471e7d00-2b5f-11eb-8c68-abf5dd4050d2.png)
编写sql 关联用户表查询：
`select * from (select a.id,a.name,b.username from test_rp a join sys_user b on a.user = b.username ) t where t.username= 'admin'`

查询正常：
![image](https://user-images.githubusercontent.com/27989856/99790749-8220b080-2b5f-11eb-80eb-f1f2b4419f9f.png)

因为我这边代码比较新，建议检查自己sql或是看看后续版本吧

**Comment by zhangdaiscott** [comment]
按照这个文档集成最新版试试
https://my.oschina.net/jeecg/blog/4779874
