### ISSUE TITLE
点打印按钮卡住

### ISSUE THREAD

**Issue by iGuozy** [zhangdaiscott/JimuReport#180]
##### 版本号：
1.2.1

##### 问题描述：
打印预览数据显示正常，但是点打印按钮后，就卡住，弹不出打印界面

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48822119/114263197-bca7be80-9a16-11eb-995c-b250df25c743.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
你需要看下控制台是否报错

**Comment by iGuozy** [comment]
控制台有报错。有个function找不到，是否缺了引入什么？
![image](https://user-images.githubusercontent.com/48822119/114293516-5d56b680-9ac9-11eb-9e78-3c1e79eae611.png)

**Comment by zhangdaiscott** [comment]
请升级到最新版本试试
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.1-beta3</version>
</dependency>
```

**Comment by iGuozy** [comment]
升到beta3就可以了，谢谢。
