### ISSUE TITLE
后续更新能否自定义超链接颜色?

### ISSUE THREAD

**Issue by korme** [zhangdaiscott/JimuReport#182]
##### 版本号：
1.3.1

##### 问题描述：
添加的超链接固定为蓝色,  蓝色背景下难以分辨, 后续能否允许自定义超链接颜色?

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/25315242/114269542-5896f180-9a3a-11eb-86c2-bdfff8946997.png)
![图片](https://user-images.githubusercontent.com/25315242/114269547-62b8f000-9a3a-11eb-8942-b68968fcf070.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
收录

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138

**Comment by tygithub1** [comment]
新版可以控制字体颜色 从而控制超链接颜色  
![image](https://user-images.githubusercontent.com/27989856/127659098-3c8805ef-b9bb-4816-97e2-ad5cc2feba0e.png)
![image](https://user-images.githubusercontent.com/27989856/127659136-ff496ff6-2d42-4e20-9f5b-482abfa4be1b.png)
