### ISSUE TITLE
macOS 环境 SnowflakeIdWorker#generateId 初始化时空指针

### ISSUE THREAD

**Issue by lumotime** [zhangdaiscott/JimuReport#184]
<span style="color: red">在 Mac OS系统中.</span>

##### 版本号：
v1.3.1-beta2

##### 问题描述：
SnowflakeIdWorker#generateId 在进行初始化时调用了SnowflakeIdWorker#getDataCenterId方法, 在 mac os系统中无法通过 SystemUtils#getHostName() 方法获取计算机名称导致后边获取 length时空指针异常. 

##### 截图&代码：
![image](https://user-images.githubusercontent.com/66256045/114357657-99ab1500-9ba4-11eb-91b4-121f04f350f1.png)

![image](https://user-images.githubusercontent.com/66256045/114358060-0faf7c00-9ba5-11eb-93e9-3aacc666e2a9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
org.jeecgframework.minidao.util.SnowflakeIdWorker
重写下这个类，看看这个写法可以吗

**Comment by lumotime** [comment]
> org.jeecgframework.minidao.util.SnowflakeIdWorker
> 重写下这个类，看看这个写法可以吗
> [SnowflakeIdWorker.zip](https://github.com/zhangdaiscott/JimuReport/files/6295355/SnowflakeIdWorker.zip)

修改如下后测试成功.
![image](https://user-images.githubusercontent.com/66256045/114479286-d887ac00-9c32-11eb-955c-6313106b2bff.png)

测试结果
![image](https://user-images.githubusercontent.com/66256045/114479371-0240d300-9c33-11eb-8314-6796bf24af25.png)

**Comment by zhangdaiscott** [comment]
就是用的上传的附件吧，没再改动吧

**Comment by lumotime** [comment]
> 就是用的上传的附件吧，没再改动吧

附件里的 ints = StringUtils.toCodePoints()应该是 hostname 而不是 SystemUtils#getHostname
