### ISSUE TITLE
api数据源的报表参数每次修改api会导致参数文本清空

### ISSUE THREAD

**Issue by qiuchendong** [zhangdaiscott/JimuReport#186]
##### 版本号：
1.3.0-beta3

##### 问题描述：
api数据源的报表参数每次修改api会导致参数文本清空,希望添加记忆功能，或者默认把参数名赋值给参数文本

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经发现问题，正在修复

**Comment by zhangdaiscott** [comment]
已经发现问题，正在修复

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/JimuReport/issues/I3IE3O
