### ISSUE TITLE
数据钻取无法使用

### ISSUE THREAD

**Issue by bgxabc** [zhangdaiscott/JimuReport#187]
##### 版本号：
1.3.1-beta3

##### 问题描述：
定义的网络报表，无法钻取，点击无反应

##### 截图&代码：
![1](https://user-images.githubusercontent.com/21749519/114493022-5310f580-9c4c-11eb-8cbe-cca646f587c0.png)

官网的示例也无法钻取
![22](https://user-images.githubusercontent.com/21749519/114493225-c0bd2180-9c4c-11eb-9688-403d94bab328.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
新版本已修复,请更新到最新版
```
<dependency> 
<groupId>org.jeecgframework.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.3.2-beta</version> 
</dependency>
```

**Comment by bgxabc** [comment]
> ##### 版本号：
> 1.3.1-beta3
> 
> ##### 问题描述：
> 定义的网络报表，无法钻取，点击无反应
> 
> ##### 截图&代码：
> ![1](https://user-images.githubusercontent.com/21749519/114493022-5310f580-9c4c-11eb-8cbe-cca646f587c0.png)
> 
> 官网的示例也无法钻取
> ![22](https://user-images.githubusercontent.com/21749519/114493225-c0bd2180-9c4c-11eb-9688-403d94bab328.png)
> 
> 早上收到邮件后进行测试，Chrome，问题仍然存在
我做了一个网络报表
![1](https://user-images.githubusercontent.com/21749519/115486145-a0aee300-a288-11eb-8b55-fffa808d1e67.png)

连接一个打印报表
![2](https://user-images.githubusercontent.com/21749519/115486151-a4426a00-a288-11eb-8bd9-ffa5b1088a31.png)

连接点了无响应，打印

![3](https://user-images.githubusercontent.com/21749519/115486169-ad333b80-a288-11eb-89d3-d21d31562983.png)
