### ISSUE TITLE
springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'designReportController': 

### ISSUE THREAD

**Issue by guren1131** [zhangdaiscott/JimuReport#188]
##### 问题描述：
springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'designReportController': Unsatisfied dependency expressed through field 'jmReportDesignService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jimuReportServiceImpl' defined in URL 

##### 截图&代码：
![222222](https://user-images.githubusercontent.com/32631049/114505115-7a72bd00-9c62-11eb-8ed2-a68d0b4f606c.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
第五步: 增加spring扫码路径
@SpringBootApplication(scanBasePackages = {"org.jeecg.modules.jmreport"})
