### ISSUE TITLE
模板案例列表中，上传封面后不成功，日志提示报错

### ISSUE THREAD

**Issue by houwei1008** [zhangdaiscott/JimuReport#189]
##### 版本号：

1.3.1-beta4
##### 问题描述：
模板案例列表中，上传封面后不成功，日志提示报错

##### 截图&代码：
: JimuReportInterceptor check requestPath = /jmreport/putFile
: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Name for argument of type [java.lang.String] not specified, and parameter name information not found in class file either.] with root cause
java.lang.IllegalArgumentException: Name for argument of type [java.lang.String] not specified, and parameter name information not found in class file either.

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
截图看你的操作

**Comment by houwei1008** [comment]
![1](https://user-images.githubusercontent.com/18042941/114509317-f1f71b00-9c67-11eb-9ae3-c0d07da03804.png)
![2](https://user-images.githubusercontent.com/18042941/114509329-f58aa200-9c67-11eb-8b49-00e9dbc87c27.png)

**Comment by zhangdaiscott** [comment]
你的版本很老了，现在最新版没这功能了

**Comment by houwei1008** [comment]
implementation 'org.jeecgframework.jimureport:spring-boot-starter-jimureport:1.3.1-beta4'

现在最新版本不是1.3.1-beta4 吗？

**Comment by zhangdaiscott** [comment]
是bug，我们尽快安排
ws

**Comment by tygithub1** [comment]
已修复
