### ISSUE TITLE
数据源配置问题

### ISSUE THREAD

**Issue by haoleday** [zhangdaiscott/JimuReport#19]
以下问题是在使用，报表设计器——打印设计下具体设计报表时，添加mysql数据源的时候遇到的问题。我不确定大家是否都有遇到同样的问题。
1、页面上添加数据源按钮操作。数据源配置只支持一个，添加第二个，第一个就被覆盖了。
2、数据配置完，测试连接通过，保存成功。但是添加sql数据集的时候，并不是访问的页面上配置的数据源的链接信息，而是走的yaml文件里面写的数据库链接。只有对应yaml文件里面的数据库的表才能查的到，才能解析成功。

**Comment by zhangdaiscott** [comment]
你升级依赖到 1.0.2-beta，这块改造过了
```
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>jimureport</artifactId>
  <version>1.0.2-beta</version>
</dependency>
```

**Comment by haoleday** [comment]
好的，我去试一下，谢谢。
