### ISSUE TITLE
oracle数据库点击数据报表报错

### ISSUE THREAD

**Issue by rose-wl** [zhangdaiscott/JimuReport#190]
##### 版本号：
1.3.1-beta4

##### 问题描述：
oracle数据库，点击数据报表报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/82435184/114506776-d8a09f80-9c64-11eb-914b-21159a109b57.png)
错误内容：org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select * from ( SELECT * FROM jimu_report jr WHERE 1=1 and jr.CREATE_BY = ? and jr.TYPE = ? and jr.DEL_FLAG = ? and jr.TEMPLATE = ? ORDER BY jr.create_time DESC) sel_tab00 limit 0,10]; nested exception is java.sql.SQLSyntaxErrorException: ORA-00933: SQL 命令未正确结束

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2213131
