### ISSUE TITLE
可不可以关闭最上面的分页控制栏

### ISSUE THREAD

**Issue by qiuchendong** [zhangdaiscott/JimuReport#191]
##### 版本号：
1.3.0-beta3

##### 截图&代码：

![image](https://user-images.githubusercontent.com/37330760/114526944-06dcaa00-9c7a-11eb-88ae-06d86c7cfe18.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
归集到
暂不支持功能归集 #138

**Comment by gelinagg** [comment]
同需求
