### ISSUE TITLE
Api数据集支持使用变量替换吗

### ISSUE THREAD

**Issue by qiuchendong** [zhangdaiscott/JimuReport#192]
##### 版本号：
1.3.0-beta3

##### 问题描述：
api接口路径中的ip:端口号/项目名  在开发、测试、生产环境都是不同的，在不同环境部署时需要手动修改jimu_report_db表的记录，希望可以在application.yaml文件中进行配置，在请求api时进行替换

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
#jeecg专用配置
jeecg :
  jmreport:
    # api请求基础路径
    apiBasePath: http://localhost:8080/jeecg-boot
