### ISSUE TITLE
表头横向分组不好用

### ISSUE THREAD

**Issue by liguo8231** [zhangdaiscott/JimuReport#193]
##### 版本号：
官网在线设计器

##### 问题描述：
通过设计器将表头设计为横向分组后，字段的值解析不了。横向扩展的效果没有。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/42465690/114554642-875ed300-9c99-11eb-95b9-8c58e26a69c9.png)
![image](https://user-images.githubusercontent.com/42465690/114554753-a2c9de00-9c99-11eb-92f3-47b801705dcf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
目前仅支持示例提供的分组用法，请严格安装示例，暂不可自行随意发挥用法

**Comment by liguo8231** [comment]
知道了，多谢。再请教个问题，示例都是利用接口的形式，如果利用SQL数据集，好像sql中的排序不生效，是sql的写法有啥特殊要求吗

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138
