### ISSUE TITLE
循环块设置保存后，无法取消

### ISSUE THREAD

**Issue by iGuozy** [zhangdaiscott/JimuReport#194]
##### 版本号：
1.3.1 beta3

##### 问题描述：
报表设置了循环块保存退出，重新打开报表格式，取消不到循环块

##### 截图&代码：
<img width="369" alt="image" src="https://user-images.githubusercontent.com/48822119/114558747-96478480-9c9d-11eb-8d57-319810b28882.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
你应该是多次设定了循环快区域造成了标记混乱，取消循环快的依据是该单元格必须有隐藏循环快标记

**Comment by llmoe** [comment]
有遇到过。。不知道咋整回复 后面删了重新做了个报表。。
