### ISSUE TITLE
升级1.3.1-beta4 后，不兼容SqlServer

### ISSUE THREAD

**Issue by iGuozy** [zhangdaiscott/JimuReport#196]
##### 版本号：
1.3.1-beta4

##### 问题描述：
在1.3.1-beta4版本把minidao升级到1.7.3，也不兼容SqlServer，在上一个版本升级minidao后，是兼容的。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48822119/114652454-7acd8f80-9d18-11eb-8bd2-064d2a9f2e31.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
minidao的db类型改了吗
![image](https://user-images.githubusercontent.com/3162115/114659205-bf135c80-9d25-11eb-94c7-94f787541f84.png)
