### ISSUE TITLE
报表参数，默认值是否可支持动态日期，并且和查询条件关联

### ISSUE THREAD

**Issue by houxinyuncut** [zhangdaiscott/JimuReport#197]
##### 版本号：
v1.3.1-beta4

##### 问题描述：
1、报表动态参数，如果参数是时间，默认值怎样设置成每次调用的当前时间
2、查询条件一般都会和设置的参数相关，这样方便控制数据集显示，和默认状态
单纯的通过URL控制参数，不太够用
##### 截图&代码：
![image](https://user-images.githubusercontent.com/39584675/114665646-deaf8280-9d2f-11eb-8d56-4fa268199510.png)
![image](https://user-images.githubusercontent.com/39584675/114665671-e707bd80-9d2f-11eb-84c6-42e8cd3c4999.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
已收录，优化中

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138
