### ISSUE TITLE
范围查询功能无效

### ISSUE THREAD

**Issue by llmoe** [zhangdaiscott/JimuReport#199]
##### 版本号：
1.3.1-beta4

##### 问题描述：
范围查询无效，想实现一个用户输入查询条件查询的功能，因为是用范围查询没错吧，但是设置后，测试无法筛选成功，查看控制台日志也没有拼接查询条件

另外想提个意见，查询能否支持自定义条件,入下图这种。另外查询的表单能否自定义使用输入框或者其他表单
<img width="173" alt="截屏2021-04-14 17 59 51" src="https://user-images.githubusercontent.com/17946937/114692463-38717600-9d4b-11eb-8446-8c33aeac0780.png">

##### 截图&代码：

<img width="917" alt="截屏2021-04-14 17 58 18" src="https://user-images.githubusercontent.com/17946937/114692206-006a3300-9d4b-11eb-97fc-a668d888e887.png">

<img width="644" alt="截屏2021-04-14 17 58 53" src="https://user-images.githubusercontent.com/17946937/114692285-14ae3000-9d4b-11eb-8c02-80ccd8d87b97.png">

<img width="1406" alt="截屏2021-04-14 18 03 05" src="https://user-images.githubusercontent.com/17946937/114692932-addd4680-9d4b-11eb-947a-7f6ad01da335.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
sql功能持续增强中，请持续关注

**Comment by tygithub1** [comment]
你告诉我 用户怎么做的范围查询

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2266239
