### ISSUE TITLE
数据报表分组 合计问题

### ISSUE THREAD

**Issue by Roffy0** [zhangdaiscott/JimuReport#20]
我们需要实现一些数据的分组还有，各分组的合计以及总计  目前看视频还有文档教程里面都没有涉及这部分。
官网报表示例各个表如果能实现就好了

**Comment by tygithub1** [comment]
后续完善 请提出你的分组合计相应的场景和截图说明 我们设计的时候看能否考虑进去

**Comment by Roffy0** [comment]
就你们官网报表那些示例
![image](https://user-images.githubusercontent.com/18276810/99208587-dfcd9980-27fb-11eb-960d-e1e55ebcd808.png)

**Comment by mini2014** [comment]
下个版本都会支持的
