### ISSUE TITLE
希望打印增加按分页打印全部的功能

### ISSUE THREAD

**Issue by wuwang494309953** [zhangdaiscott/JimuReport#200]
##### 版本号：
1.2.0

##### 问题描述：
希望打印增加按分页打印全部的功能。目前的打印全部是接口请求添加**printAll**字段，后台返回全部数据的打印，期望的效果是按预览分页的效果打印两页

##### 截图&代码：
![image](https://user-images.githubusercontent.com/14356895/114806416-4ec51380-9dd7-11eb-848b-c2290d89134f.png)
![image](https://user-images.githubusercontent.com/14356895/114806477-68fef180-9dd7-11eb-9570-a449dfbb6a50.png)

**现在打打印全部：**
![image](https://user-images.githubusercontent.com/14356895/114806761-d874e100-9dd7-11eb-8e35-2a45fd267cc2.png)

**期望的打印全部：**
  如截图，期望的全部打印是打印两张和预览一样的单据，而不只是中间的列表的数据返回了全部

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改，等下个版本吧
正常请求，如果分页查询，需要将总数作为参数count传给报表，那么打印全部的时候，报表会拿到count的作为pageSize的值查询。
