### ISSUE TITLE
使用系统变量占位符#{} 书写SQL数据集，出现的问题。望解答

### ISSUE THREAD

**Issue by qwe8324868** [zhangdaiscott/JimuReport#203]
##### 版本号：
V 1.3.1

##### 问题描述：
SQL数据集使用 系统变量 占位符 #{}  书写的SQL 无法在 饼状图，柱状图等图形设计里面直接引用，会报错
##### 截图&代码：
第一张图是报错信息
![1](https://user-images.githubusercontent.com/38347433/114853798-bf3f5500-9e16-11eb-855b-b391ce64c340.png)

第二张图是SQL数据集样子
![2](https://user-images.githubusercontent.com/38347433/114853802-c0708200-9e16-11eb-9184-3a6846140ed5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
待分析

**Comment by qwe8324868** [comment]
> 待分析

目前不支持是吗

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改
