### ISSUE TITLE
建议数据源在后台设置，有完整的用户登录体系

### ISSUE THREAD

**Issue by kuaile1993** [zhangdaiscott/JimuReport#204]
##### 问题描述：
建议数据源在后台设置，有完整的用户登录体系，全部放在前台配置，数据库不安全。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/52553619/114982781-71802680-9ec2-11eb-8fa6-1a2dfd7a2882.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
感谢建议

**Comment by mini2014** [comment]
先归集到==> 暂不支持功能归集 #138
