### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by sxs0905** [zhangdaiscott/JimuReport#207]
##### 版本号：
版本号如图所示
![image](https://user-images.githubusercontent.com/10756598/115213491-240af000-a134-11eb-909c-989167f4627c.png)

##### 问题描述：
SQL数据集，填写完报表SQL并点击SQL解析，动态报表明细字段以及数据预览的表头与当前SQL语句查出来的字段不匹配(是第一次执行SQL解析时查出来的字段)
第二次执行只保留一个字段,通过开发者工具查看,接口返回正确,但是页面没更新

##### 截图&代码：

![image](https://user-images.githubusercontent.com/10756598/115212843-86172580-a133-11eb-8912-9658788d6403.png)
这是第二次SQL查询语句,页面展示结果和上面的sql解析结果展示的一样
![image](https://user-images.githubusercontent.com/10756598/115213114-cb3b5780-a133-11eb-8226-1400b26549d3.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by jackshenjunkai** [comment]
在设计器界面点击对应列，右侧的属性面板也不更新

**Comment by zhangdaiscott** [comment]
发布最新版本JAR(注意配置jeecg私服)
```
<dependency> 
<groupId>org.jeecgframework.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.3.2-beta</version> 
</dependency>
```
