### ISSUE TITLE
2.1.3版本的jeecgboot token一直提示失效

### ISSUE THREAD

**Issue by Roffy0** [zhangdaiscott/JimuReport#21]
我本来在TokenUtils直接处理掉链接，可以新增报表 但是数据源会查找create_by 这个会值null 查找不到东西 新增不了sql集，怎么处理

**Comment by zhangdaiscott** [comment]
错误日志帖一下

**Comment by liusk98** [comment]
> 错误日志帖一下

java.lang.NoSuchMethodError: org.jeecg.common.util.TokenUtils.verifyToken(Ljavax/servlet/http/HttpServletRequest;Lorg/jeecg/common/api/CommonAPI;Lorg/jeecg/common/util/RedisUtil;)Z
	at org.jeecg.modules.jmreport.desreport.a.a.e(DesignReportController.java:1231)

**Comment by zhangdaiscott** [comment]
升级1.1-beta版本就好了
https://my.oschina.net/jeecg/blog/4779874
