### ISSUE TITLE
本地使用idea调试正常，jar包发布到服务器上报错如下

### ISSUE THREAD

**Issue by houwei1008** [zhangdaiscott/JimuReport#211]
##### 版本号：
1.3.1-beta4

##### 问题描述：
新增报表的时候，调用/jmreport/save 报错

##### 截图&代码：
![1](https://user-images.githubusercontent.com/18042941/115357510-49106900-a1ef-11eb-9d5d-ca0a395ad181.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by houwei1008** [comment]
还有就是 添加sql数据集，采用数据源的时候，点击保存按钮也容易报错
![3](https://user-images.githubusercontent.com/18042941/115361021-c2f62180-a1f2-11eb-998e-db41d2c42ace.png)
![2](https://user-images.githubusercontent.com/18042941/115361037-c689a880-a1f2-11eb-8baf-0c13093c6e12.png)

**Comment by houxinyuncut** [comment]
我也遇到过，mysql驱动问题，POM 升级一个数据库驱动版本就可以

**Comment by houwei1008** [comment]
我是使用Oracle数据库的，采用的是Oracle驱动
    runtimeOnly 'com.oracle.ojdbc:ojdbc8'
    runtimeOnly 'com.oracle.ojdbc:orai18n'

**Comment by zhangdaiscott** [comment]
引入最新版本
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.2-beta</version>
</dependency>
```
