### ISSUE TITLE
JimuReportTokenService 缺少部分类源码

### ISSUE THREAD

**Issue by mauersu** [zhangdaiscott/JimuReport#212]
##### 版本号：

1.3.1-beta4

##### 问题描述：

JimuReportTokenService 缺少部分类源码

##### 截图&代码：

![image](https://user-images.githubusercontent.com/2222181/115482237-c637ee80-a280-11eb-9452-54384d095e2f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
参考改，不是原样，这是jeecgboot的集成写法
