### ISSUE TITLE
> ##### 版本号：1.3.2-beta

### ISSUE THREAD

**Issue by bgxabc** [zhangdaiscott/JimuReport#213]
早上收到邮件后进行测试，Chrome，问题仍然存在（官网示例中可以点击，但不知道是否是网络报表）
我做了一个网络报表
![1](https://user-images.githubusercontent.com/21749519/115486145-a0aee300-a288-11eb-8b55-fffa808d1e67.png)

连接一个打印报表
![2](https://user-images.githubusercontent.com/21749519/115486151-a4426a00-a288-11eb-8bd9-ffa5b1088a31.png)

连接点了无响应，打印

![3](https://user-images.githubusercontent.com/21749519/115486169-ad333b80-a288-11eb-89d3-d21d31562983.png)

> ##### 版本号：
> 1.3.2-beta
> 
> ##### 问题描述：
> 定义的网络报表，无法钻取，点击无反应
> 
> ##### 截图&代码：
> ![1](https://user-images.githubusercontent.com/21749519/114493022-5310f580-9c4c-11eb-8cbe-cca646f587c0.png)
> 
> 官网的示例也无法钻取
> ![22](https://user-images.githubusercontent.com/21749519/114493225-c0bd2180-9c4c-11eb-9688-403d94bab328.png)
> 

_Originally posted by @bgxabc in https://github.com/zhangdaiscott/JimuReport/issues/187#issuecomment-823719037_

**Comment by 1298191366** [comment]
刚才我刚才点了一下官网钻取可以使用，或者说浏览器禁止弹窗了
![image](https://user-images.githubusercontent.com/30997828/115486917-30a15c80-a28a-11eb-9eaa-71deed053259.png)
![image](https://user-images.githubusercontent.com/30997828/115486930-372fd400-a28a-11eb-857c-2d0355a31d8e.png)

**Comment by 1298191366** [comment]
不行的话刷新一下浏览器缓存

**Comment by bgxabc** [comment]
缓存是清理过的，这是控制台打印

这会儿官网无法使用



***@***.***
 
发件人： wangshuai
发送时间： 2021-04-21 10:14
收件人： zhangdaiscott/JimuReport
抄送： bgxabc; Mention
主题： Re: [zhangdaiscott/JimuReport] > ##### 版本号：1.3.2-beta (#213)
不行的话刷新一下浏览器缓存

**Comment by 1298191366** [comment]
你把重复的id删除一下你试试

**Comment by 1298191366** [comment]
如果还是不行的话看看能不能再官网复现，我这里暂时无法复现

**Comment by bgxabc** [comment]
我本地只有一条记录，解析后会出现两个ID，而且是一样的ID。
附件是我的项目和数据库脚本。



***@***.***
 
发件人： wangshuai
发送时间： 2021-04-21 20:08
收件人： zhangdaiscott/JimuReport
抄送： bgxabc; Mention
主题： Re: [zhangdaiscott/JimuReport] > ##### 版本号：1.3.2-beta (#213)
如果还是不行的话看看能不能再官网复现，我这里暂时无法复现

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
最新版本已修复，注意要配上私服
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
