### ISSUE TITLE
图表联动无法绑定  上传封面功能没有开发完吗

### ISSUE THREAD

**Issue by YuZhengGitHub888** [zhangdaiscott/JimuReport#214]
##### 问题描述：一、图表联动无法绑定  我记得上一个版本是可以的
二、上传封面功能是没有开发完吗

##### 截图&代码：
第一个问题：
![image](https://user-images.githubusercontent.com/64897973/115491718-115afd00-a293-11eb-89f9-a1719a2bca00.png)
![image](https://user-images.githubusercontent.com/64897973/115491885-5ed76a00-a293-11eb-8c21-a371f0d14272.png)
第二个问题：
![image](https://user-images.githubusercontent.com/64897973/115492033-98a87080-a293-11eb-900e-fc8f75f01725.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
发布最新版本JAR(注意配置jeecg私服)
```
<dependency> 
<groupId>org.jeecgframework.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.3.2-beta</version> 
</dependency>
```

**Comment by YuZhengGitHub888** [comment]
可以绑定成功了  但是点击列表数据时 图表并没有更新数据
点击列表数据时  报以下错误 
![image](https://user-images.githubusercontent.com/64897973/115641618-057f4180-a34c-11eb-857a-fd6db9a10569.png)

**Comment by zhangdaiscott** [comment]
升级到这个版本看看
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
有升级脚本，具体见http://jimureport.com/doc/log
