### ISSUE TITLE
SQL数据集，动态参数与查询条件不能有效配合，动态控制数据集大小

### ISSUE THREAD

**Issue by houxinyuncut** [zhangdaiscott/JimuReport#216]
##### 版本号：
1.3.2-beta

##### 问题描述：
SQL数据集  动态参数，如果是配置成菜单让用户用；用户是通过查询条件交互，但是如果查询条件是用户控制数据集，比如时间段；查询条件和动态参数是无关；要满足用户这种需求，就需要全量获取数据库数据；如果数据量大会有性能问题。

##### 截图&代码：
SQL数据集；不能够通过查询条件，动态获取范围

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
说下你有什么好的建议
