### ISSUE TITLE
使用API 数据集，token值一直是null

### ISSUE THREAD

**Issue by hansen1160** [zhangdaiscott/JimuReport#217]
##### 版本号：
1.3.1-beta4

##### 问题描述：
使用API 数据集，Apis解析的时候token值传不到后台

##### 截图&代码：
![image](https://user-images.githubusercontent.com/63092991/115660412-8ea77000-a36e-11eb-8604-43a890aa2a25.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
二、 自定义鉴权
如果不自定义，则积木报表所有请求都不做权限控制
Jeecgboot请复制类 JimuReportTokenService.java到项目中即可（类路径org.jeecg.config.jimureport），其他项目参考改造。
访问地址： {项目前缀}/jmreport/list?token=${token}

http://report.jeecg.com/2078875
