### ISSUE TITLE
报表主页的预览模版功能，点击后跳转页面未携带Token

### ISSUE THREAD

**Issue by zioang** [zhangdaiscott/JimuReport#218]
##### 版本号：
1.3.1-beta4

##### 问题描述：
在报表设计器页面点击预览模版后，页面跳转到对应模版展示窗口时，未携带 token。

##### 截图&代码：

- 报表设计器页面:

![image](https://user-images.githubusercontent.com/24779737/115686093-6a0dc100-a38b-11eb-8831-5c664f9b244b.png)

- 设计模版页面：
![image](https://user-images.githubusercontent.com/24779737/115686223-8f9aca80-a38b-11eb-941e-ce28609ca0f5.png)

- 预览模版页面（问题所在页面）：
![image](https://user-images.githubusercontent.com/24779737/115686282-9f1a1380-a38b-11eb-9f54-d39bbf957f06.png)

自己重写了 JmReportTokenServiceI，但基本无变动。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
手工拼上

**Comment by zioang** [comment]
> 手工拼上

![image](https://user-images.githubusercontent.com/24779737/115692163-506f7800-a391-11eb-8207-835567b1d00b.png)
我想知道的是目前有没有解决方案，手工拼上我也知道啊....这应该是页面模版没加上的原因吧？新版本有修复吗？

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改，1.3.3-beta版本之后发布
