### ISSUE TITLE
图表页面渲染问题

### ISSUE THREAD

**Issue by zioang** [zhangdaiscott/JimuReport#219]
##### 版本号：
1.3.1-beta4
macos big sur
chrome 90.0.4430.85
##### 问题描述：

1. 在设计时给定图表位置，但是显示时不在指定位置上。
2. 普通柱形图，如果鼠标一直停留在某列数据上，那列的图形会消失。

##### 截图&代码：

1. 
![image](https://user-images.githubusercontent.com/24779737/115804843-6410f200-a416-11eb-92f5-0d00a7b4e417.png)
![image](https://user-images.githubusercontent.com/24779737/115804863-6f641d80-a416-11eb-8e2d-55997e6c6335.png)

2.
![image](https://user-images.githubusercontent.com/24779737/115804909-7f7bfd00-a416-11eb-99e1-7454d7bf50c3.png)
 

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
待分析
