### ISSUE TITLE
主子报表批量查询(SQL数据集)

### ISSUE THREAD

**Issue by tiangang-ctg** [zhangdaiscott/JimuReport#220]
##### 版本号：

1.3.1-beta4

##### 问题描述：

主子报表实现多条主子数据查询
例如我现在有一个生产订单头表(主表)和生产订单行表(子表)
目前只能查询一个生产订单头信息和行信息
我想要实现 查询多个生产订单展示出来

##### 截图&代码：

![image](https://user-images.githubusercontent.com/68258234/115826027-df859a00-a43c-11eb-834e-2c75d93aeca5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
已规划解析嵌套数据源问题

**Comment by tiangang-ctg** [comment]
> 已规划解析嵌套数据源问题
下个版本可以更新吗  然后下个版本更新大概是什么时候

**Comment by zhangdaiscott** [comment]
你想循环展示？说明你要的展示方式

**Comment by tiangang-ctg** [comment]
> 你想循环展示？说明你要的展示方式
我现在有两张表  order_header(生成订单头主表)   order_item(生产订单行子表) 两张表有个外键关联字段为订单编号 ，我想要查询这两张表的信息展示
然后我看你们的主子报表 好像可以实现我的需求 然后我就试了下 结果是只可以查询数据库某一个生产订单的主子信息展示(参考上面截图)，也就是必须传一个订单编号的参数
但是我的主表会有很多生产订单，所以我现在想要实现不传任何参数 ，直接查询数据库所有生产订单的主子信息 分页展示出来，

**Comment by zhangdaiscott** [comment]
最新版已经支持 http://report.jeecg.com/2290863
