### ISSUE TITLE
Excel导出时，js报500

### ISSUE THREAD

**Issue by mojiezsy** [zhangdaiscott/JimuReport#224]
##### 版本号：
1.3.1-beta4
##### 问题描述：
Excel导出前台报错500。
目前发现依赖了spring-boot-starter-undertow都会有这个问题。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/83196014/116022147-3200c980-a67c-11eb-8bf9-7a3c888bfe4e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请发详细错误

**Comment by 1298191366** [comment]
已修复，待新版本发布
