### ISSUE TITLE
报表设计右侧菜单联动问题

### ISSUE THREAD

**Issue by mojiezsy** [zhangdaiscott/JimuReport#225]
##### 版本号：
1.3.1-beta4

##### 问题描述：
点击表格，右侧数值没有跟着变

##### 截图&代码：

![XDW 6 I {N )I_GG}S}(Z0](https://user-images.githubusercontent.com/83196014/116023527-d84dce80-a67e-11eb-8b76-78893638d12b.jpg)

**Comment by accpman** [comment]
待分析-ty

**Comment by zhangdaiscott** [comment]
升级到这个版本看看
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
有升级脚本，具体见http://jimureport.com/doc/log
