### ISSUE TITLE
模版内容解析错误

### ISSUE THREAD

**Issue by zioang** [zhangdaiscott/JimuReport#226]
##### 版本号：
1.3.1-beta4

##### 问题描述：
使用含字符串字段的 SQL 数据集时，保存到数据库中的模版JSON字符串是正确的，但是在解析过程中字符串字段解析出错。

经测试发现，数据报表会报这个错，打印表不会。

##### 截图&代码：

**SQL 数据集：**

![image](https://user-images.githubusercontent.com/24779737/116034136-5ddc7900-a695-11eb-8f8a-dcc9a01b9bae.png)

**数据库中对应的片段:**

![image](https://user-images.githubusercontent.com/24779737/116034187-7482d000-a695-11eb-9875-474a944dbd7f.png)

**解析过程出错:**

![image](https://user-images.githubusercontent.com/24779737/116034332-aeec6d00-a695-11eb-9d85-5c836ae05838.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
待分析-ws

**Comment by 1298191366** [comment]
你数据库中的数据是怎样存储的，可以把你的数据给我一份吗，或者是否在线上造一个例子，我这里测试没有问题

**Comment by zhangdaiscott** [comment]
升级到这个版本看看
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
有升级脚本，具体见http://jimureport.com/doc/log
