### ISSUE TITLE
下钻报表参数问题

### ISSUE THREAD

**Issue by gaga-mj** [zhangdaiscott/JimuReport#227]
##### 问题描述：下钻报表参数传递可以传api 接口带的参数吗？
现在例子中下钻报表只能带单元格中的内容，那其他查询条件没有在单元格中显示的，如何传递

##### 截图&代码：没有代码

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
后续优化

**Comment by zhangdaiscott** [comment]
新版已经支持
