### ISSUE TITLE
建议api数据源编辑界面加上设置header的功能

### ISSUE THREAD

**Issue by truthsun22** [zhangdaiscott/JimuReport#23]
api设置数据源，如果访问本地jeecgboot服务的话，需要传token，token是放在header里的。目前只能是shrio放开接口访问一个办法

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
已修改

**Comment by zhangdaiscott** [comment]
按照这个文档集成，已经发布
https://my.oschina.net/jeecg/blog/4779874
