### ISSUE TITLE
导出excel时，图片未导出

### ISSUE THREAD

**Issue by guopanwang** [zhangdaiscott/JimuReport#230]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/37395229/116170216-f2e47e00-a738-11eb-9244-3ebb5686543e.png)

![image](https://user-images.githubusercontent.com/37395229/116170157-d7797300-a738-11eb-9e7b-7b28df9a24ce.png)

**Comment by accpman** [comment]
多测试几个图片

**Comment by zhangdaiscott** [comment]
升级到这个版本看看
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
有升级脚本，具体见http://jimureport.com/doc/log

**Comment by 1298191366** [comment]
本地图片支持导出以支持，待新版本发布
