### ISSUE TITLE
配置文件优先级问题

### ISSUE THREAD

**Issue by mojiezsy** [zhangdaiscott/JimuReport#231]
##### 版本号：
1.3.2-beta

##### 问题描述：
config路径下的配置文件优先级过高，覆盖了原项目的配置

##### 截图&代码：

![image](https://user-images.githubusercontent.com/83196014/116181753-bd965b00-a74d-11eb-87d3-cac5c9780809.png)

**Comment by accpman** [comment]
待分析-ws

**Comment by accpman** [comment]
待分析-ws

**Comment by zhangdaiscott** [comment]
不会啊，肯定是你自己的配置优先级高啊

**Comment by zhangdaiscott** [comment]
升级到这个版本看看
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
有升级脚本，具体见http://jimureport.com/doc/log
