### ISSUE TITLE
macOS 开启项目获取不到hostname

### ISSUE THREAD

**Issue by chenmanj** [zhangdaiscott/JimuReport#234]
##### 截图&代码：
    private static Long getDataCenterId(){
        int[] ints = StringUtils.toCodePoints(SystemUtils.getHostName());
        int sums = 0;
        for (int i: ints) {
            sums += i;
        }
        return (long)(sums % 32);
    }

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
发布最新版本JAR(注意配置jeecg私服)
```
<dependency> 
<groupId>org.jeecgframework.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.3.2-beta</version> 
</dependency>
```
