### ISSUE TITLE
apiUrl为空

### ISSUE THREAD

**Issue by wangleigithub** [zhangdaiscott/JimuReport#235]
##### 版本号：
1.2.1

##### 问题描述：
制作API数据集后，加入菜单，但是用户退出后，再进入的时候，点击菜单中的报表，进入后show方法中apiUrl参数为空了....

##### 截图&代码：

![image](https://user-images.githubusercontent.com/755879/116638056-07728180-a998-11eb-9c73-0339bffcae6e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wangleigithub** [comment]
补充一下，再次进入jmreport/list后，这个apiUrl就不为空了，怀疑和token有关系

**Comment by zhangdaiscott** [comment]
apiurl是怎么配置的

**Comment by wangleigithub** [comment]
可能是因为超时了，话说这个超时在哪里设置的？

**Comment by zhangdaiscott** [comment]
请尝试最新版
