### ISSUE TITLE
图表使用第三方数据源报错

### ISSUE THREAD

**Issue by liaobaoxin** [zhangdaiscott/JimuReport#24]
你好！
表格上使用没有问题
![image](https://user-images.githubusercontent.com/31310075/99645083-b88bfc00-2a89-11eb-86c6-61c7a2715375.png)
![2LY{L)9SPJCLQI(}17$)}VI](https://user-images.githubusercontent.com/31310075/99645112-c477be00-2a89-11eb-8bac-1df22880bcce.png)
这个是要在哪里配置下吗？

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
