### ISSUE TITLE
打印全部问题

### ISSUE THREAD

**Issue by chenmanj** [zhangdaiscott/JimuReport#240]
##### 问题描述：
1、已经分页预览，点击打印全部还是没有分页打印，全部挤在一个页面。
2、打印空白表格出现错乱，表格没有了。

#####  #截图&代码：
![images2](https://user-images.githubusercontent.com/46064517/117271131-7a926100-ae8c-11eb-8d9c-4dabd2fdf447.png)
![images1](https://user-images.githubusercontent.com/46064517/117271132-7a926100-ae8c-11eb-9429-1a8ea687c317.jpg)

![空白表格打印出现错乱](https://user-images.githubusercontent.com/46064517/117271922-3eabcb80-ae8d-11eb-8ca4-b2e1bce9b0d5.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
待分析ws

**Comment by 1298191366** [comment]
1、目前打印全部没有分页，你可以打印当前页，用参数进行传递
2、第二张图是怎么重现出来了，请提供一下数据

**Comment by chenmanj** [comment]
数据已上传

**Comment by 1298191366** [comment]
如果是放到了积木官网，请提供一下id

**Comment by chenmanj** [comment]
不好意思，网络卡了，没有上传到sql文件
sql文件：[jimu.txt](https://github.com/zhangdaiscott/JimuReport/files/6457181/jimu.txt)

**Comment by zhangdaiscott** [comment]
升级到这个版本看看
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
有升级脚本，具体见http://jimureport.com/doc/log
