### ISSUE TITLE
若依分离版集成积木报表问题

### ISSUE THREAD

**Issue by hefei-SXQ** [zhangdaiscott/JimuReport#242]
##### 版本号：
1.3.21-beta

##### 问题描述：

使用若依前后端分离版集成积木报表，前端使用里代理，代理后的后端地址为：localhost/dev-api，集成后积木报表的访问地址是：http://localhost/dev-api/jmreport/list，
页面加载不出来，因为页面中引入的其他静态资源访问地址中没有加上/dev-api的项目名，例如vuejs文件的访问路径：http://localhost/jmreport/desreport_/cdn/vue/vue.min.js，
实际的访问路径应该是：http://localhost/dev-api/jmreport/desreport_/cdn/vue/vue.min.js。麻烦看下如何解决

##### 截图&代码：

![image](https://user-images.githubusercontent.com/45480106/117432909-75e9ad80-af5d-11eb-9d30-3f5620491214.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
springboot配置了这个了吗
```
spring:
  resource:
    static-locations: classpath:/static/,classpath:/public/
```

**Comment by hefei-SXQ** [comment]
> static-path-pattern

静态资源的路径已经设置了，现在的问题是静态资源的访问路径中没有自动带上项目名/dev-api。

**Comment by zhangdaiscott** [comment]
request.getContextPath()
这个获取的是什么

**Comment by 1298191366** [comment]
我这个是vue分离版的，直接访问list是没有问题的，你的项目看看是哪里做了什么处理，如果浏览器上没有项目名，你可以在后台写个拦截器判断一下自己加上项目名
![image](https://user-images.githubusercontent.com/30997828/118444597-ecd23380-b71f-11eb-9ad4-44bbfe43cfa9.png)
![image](https://user-images.githubusercontent.com/30997828/118444257-7d5c4400-b71f-11eb-89aa-f134bd5cd14e.png)
