### ISSUE TITLE
打印页面没有纵向横向切换

### ISSUE THREAD

**Issue by chenshan07073311** [zhangdaiscott/JimuReport#245]
##### 问题描述：
打印下面设置没有横向 纵向切换

##### 截图&代码：
![image](https://user-images.githubusercontent.com/27768927/117616174-5a6ce580-b19d-11eb-8503-5269a37dcdcd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
马上会出新版，支持设计的时候设置
