### ISSUE TITLE
打印自带灰色背景

### ISSUE THREAD

**Issue by DHZHY** [zhangdaiscott/JimuReport#246]
##### 问题描述：预览是正常的，打印自带灰色背景。
在线版本也是有这个问题。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by DHZHY** [comment]
![微信图片_20210510192027](https://user-images.githubusercontent.com/37007823/117651729-dcbcd000-b1c4-11eb-93b2-3f25edaff37b.png)
![微信图片_20210510192046](https://user-images.githubusercontent.com/37007823/117651735-de869380-b1c4-11eb-9acf-05354e636581.jpg)

**Comment by DHZHY** [comment]
预览是正常的，打印出来有背景色。

**Comment by zhangdaiscott** [comment]
升级到这个版本看看
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
有升级脚本，具体见http://jimureport.com/doc/log
