### ISSUE TITLE
保存失败问题

### ISSUE THREAD

**Issue by SEJJA3** [zhangdaiscott/JimuReport#250]
##### 版本号：
1.3.1-beta4

##### 问题描述：
报表第二次进入后保存会报错,只调用了/jmreport/excelQueryName接口

##### 截图&代码：
![image](https://user-images.githubusercontent.com/62530244/117911142-d4bd7700-b30f-11eb-9040-570e3abc2dd8.png)
![image](https://user-images.githubusercontent.com/62530244/117911297-1d753000-b310-11eb-8e51-aa3ec97a4b26.png)

这是后台报的错

![image](https://user-images.githubusercontent.com/62530244/117911205-f4549f80-b30f-11eb-8542-c8028e693500.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级到这个版本看看
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
有升级脚本，具体见http://jimureport.com/doc/log

**Comment by SEJJA3** [comment]
是项目接收前端数据时,把null自动转换成""的问题

**Comment by zhangdaiscott** [comment]
最新版也有问题吗

**Comment by SEJJA3** [comment]
没有问题,是公司项目配了jackson的转换,前端参数为null时会转成""

**Comment by zhangdaiscott** [comment]
哪此问题关闭了
