### ISSUE TITLE
undertow容器，excel导出功能不好使

### ISSUE THREAD

**Issue by mojiezsy** [zhangdaiscott/JimuReport#255]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/83196014/118243759-5d374580-b4d1-11eb-8e19-ef5f0f8d6f02.png)

![image](https://user-images.githubusercontent.com/83196014/118244376-0b42ef80-b4d2-11eb-8eb5-4422e62c1042.png)

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
