### ISSUE TITLE
查询框大小不一致

### ISSUE THREAD

**Issue by liangqipang** [zhangdaiscott/JimuReport#257]
##### 版本号：
1.3.3

##### 问题描述：
查询框能否做到长和宽一至，大的大小的小真的不好看

##### 截图&代码：

![image](https://user-images.githubusercontent.com/28621242/118462870-b69daf80-b731-11eb-8e96-39bcd0e31602.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
配置页面贴出来

**Comment by 1298191366** [comment]
已优化，待下版本发布
