### ISSUE TITLE
建议加一个图片转换函数

### ISSUE THREAD

**Issue by MiXiSoReLaMi** [zhangdaiscott/JimuReport#259]
##### 版本号：
1.3.3-beta

##### 问题描述：
建议加一个图片转换函数,
如果一个表上有公司公章,如果能从数据库中将图片地址直接转换成图片处理,那么不同公司的报表可以不用手动添加公章图片

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
单元格的图片支持使用表达式

**Comment by MiXiSoReLaMi** [comment]
感谢,但是如果我想了解这个图片能不能覆盖在文字上面呢
很多带公章的都是这样子的哈

**Comment by tygithub1** [comment]
覆盖的图片，不支持动态的

**Comment by MiXiSoReLaMi** [comment]
能不能考虑支持下这个功能?

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138
