### ISSUE TITLE
springboot项目集成报空指针

### ISSUE THREAD

**Issue by chenbing2956** [zhangdaiscott/JimuReport#260]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/49462680/118623256-a3a2e200-b7fa-11eb-8f33-924c23d1175d.png)

![image](https://user-images.githubusercontent.com/49462680/118623412-cdf49f80-b7fa-11eb-83c3-e441fb341697.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
springjdbc是不是开启了多数据源

**Comment by chenbing2956** [comment]
![Uploading image.png…]()

**Comment by chenbing2956** [comment]
![Uploading image.png…]()

**Comment by chenbing2956** [comment]
![image](https://user-images.githubusercontent.com/49462680/118744591-2f625000-b887-11eb-92b8-7ee609121d4d.png)

**Comment by chenbing2956** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月18日(星期二) 晚上7:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaiscott/JimuReport] springboot项目集成报空指针 (#260)





 
springjdbc是不是开启了多数据源

**Comment by zhangdaiscott** [comment]
解决方案
https://github.com/zhangdaiscott/JimuReport/issues/170
