### ISSUE TITLE
查看报表时SQL server不兼容的语法错误

### ISSUE THREAD

**Issue by eyuan** [zhangdaiscott/JimuReport#261]
##### 问题描述：SQL server不兼容的语法错误
1.3.1的问题怎么到了1.3.3又出现了。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1910132/118636406-419ca980-b807-11eb-8750-a2c7ecf52a43.png)

rg.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [select * from ( SELECT * FROM jimu_report jr WHERE 1=1 and jr.CREATE_BY = ? and jr.TYPE = ? and jr.DEL_FLAG = ? and jr.TEMPLATE = ? ORDER BY jr.create_time DESC) sel_tab00 limit 0,10]; SQL state [S0001]; error code [1033]; 除非另外还指定了 TOP、OFFSET 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 除非另外还指定了 TOP、OFFSET 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
一直就不支持，需要自己加top处理
