### ISSUE TITLE
mysql解密函数解密后的数据不正常显示

### ISSUE THREAD

**Issue by MiXiSoReLaMi** [zhangdaiscott/JimuReport#262]
##### 版本号：
1.3.3-beta
mysql 8

##### 问题描述：
使用以下Sql查询出来的数据不能正常在页面上显示,数据预览正常显示
select AES_DECRYPT(unhex(c.name), 'xxxxxx')  from company 

##### 截图&代码：
数据预览:
![image](https://user-images.githubusercontent.com/71490260/118763555-9d6c3e80-b8aa-11eb-9c1c-b7c9d010bc2a.png)
报表预览不正常了:
![image](https://user-images.githubusercontent.com/71490260/118763750-f50aaa00-b8aa-11eb-8475-1515d6ca0bd5.png)

**Comment by tygithub1** [comment]
收录ws

**Comment by MiXiSoReLaMi** [comment]
这个问题解决到发布要多久,下个版本会不会修复? 急用

**Comment by 1298191366** [comment]
已优化，待下版本发布
