### ISSUE TITLE
能不能增加数据源类型

### ISSUE THREAD

**Issue by caiiansheng** [zhangdaiscott/JimuReport#263]
##### 版本号：
所有版本

##### 问题描述：
报表设计常用的数据库Presto ,kylin,ClickHouse数据库，有没有计划支持

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138

**Comment by jeecgos** [comment]
ClickHouse （v1.9.1已支持）
