### ISSUE TITLE
预览分页查询超出页数，未重置当前页

### ISSUE THREAD

**Issue by guopanwang** [zhangdaiscott/JimuReport#264]
##### 版本号：
1.3.3-beta

##### 问题描述：
预览界面，分页查询，选择每页条数增加时超出页数，未重置当前页

##### 截图&代码：
![image](https://user-images.githubusercontent.com/37395229/118770455-eb397480-b8b3-11eb-81c2-188b02297b70.png)
![image](https://user-images.githubusercontent.com/37395229/118770490-f9879080-b8b3-11eb-9306-019e7eaf1636.png)

**Comment by tygithub1** [comment]
根据所选 查询第8页，每页显示30条数据，结果没有数据，正常情况，不知道你说的重置是什么意思

**Comment by guopanwang** [comment]
> 根据所选 查询第8页，每页显示30条数据，结果没有数据，正常情况，不知道你说的重置是什么意思

本来 查询第八页，每页显示10条数据，有数据；然后再选择每页显示30条，查询的还是第八页的，因为超出页数，所以结果没有数据，这个不应该优化为超出页数时，就重置查询第一页或者最后一页吗
