### ISSUE TITLE
积木报表功能建议 =》标签打印功能

### ISSUE THREAD

**Issue by jyh11111** [zhangdaiscott/JimuReport#27]
-  报表添加自定义纸张尺寸 例：100 * 70 
-  报表添加打印条码，二维码功能
-  分栏打印能有吗？

_ 不是我要求太多，实在是对大神们的景仰犹如滔滔江水连绵不绝_

**Comment by mini2014** [comment]
前两个有，第三个我们收到了，我们会考虑加上，谢谢建议！
