### ISSUE TITLE
sql结果集中某字段有json格式数据时数据报表预览报错

### ISSUE THREAD

**Issue by hoowhoami** [zhangdaiscott/JimuReport#270]
##### 版本号：
1.3.3.beta

##### 问题描述：
数据报表在点击预览的时候报错
syntax error, string

##### 截图&代码：
后台抛出异常
com.alibaba.fastjson.JSONException: syntax error, string

![iShot2021-05-20 16 13 28](https://user-images.githubusercontent.com/84499551/118943603-5bb0c600-b986-11eb-807c-622dfff77016.png)
![iShot2021-05-20 16 14 11](https://user-images.githubusercontent.com/84499551/118943711-73884a00-b986-11eb-87ab-a0d38abc8808.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
收录ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
