### ISSUE TITLE
MemberAccess implementation must be provided!

### ISSUE THREAD

**Issue by jueding920** [zhangdaiscott/JimuReport#273]
##### 版本号：
1.3.3-beta

##### 问题描述：
Springboot2.2.7集成打开报表设计界面报java.lang.RuntimeException: MemberAccess implementation must be provided!

##### 截图&代码：

![image](https://user-images.githubusercontent.com/2225789/119110630-f546a900-ba54-11eb-9550-4e7a36d4cf8e.png)

**Comment by 1298191366** [comment]
我集成2.2.7.RELEASE没有报这个错误，你是不是本地集成jar冲突了
![image](https://user-images.githubusercontent.com/30997828/120630658-9e4fc380-c499-11eb-948f-41b060a45657.png)
![image](https://user-images.githubusercontent.com/30997828/120630548-8710d600-c499-11eb-9140-05e6875cad2d.png)

**Comment by jueding920** [comment]
这个支持Oracle吧？我升级到1.3.4也是一样 看了没有冲突的

**Comment by 1298191366** [comment]
支持oracle，可能是你的项目有那个jar不对，引发的，这个我也不清楚，我百度了一下说：Ognl更新到3.2.6之后，出现了MemberAccess implementation must be provided!这个异常，信息量太少，无法定位到问题，要不就把你项目上传一下

**Comment by 1298191366** [comment]
或者你新建一个springboot项目，试一试，我是新建的，集成没有问题
