### ISSUE TITLE
积木报表不支持MYSQL内置函数，视图解析时出错

### ISSUE THREAD

**Issue by hipanda51** [zhangdaiscott/JimuReport#277]
##### 版本号：

<version>1.3.3-beta</version>

##### 问题描述：

问题1、报表设计器里，不支持内置函数，比如distinct，count，其中distinct 在保存预览后能出正常结果，编辑预览没有达到预计结果，如下图1，图2
问题2、针对视图查询，在报表设计里，如果使用视图查询，解析出错，如图3（数据库查询正常）、图4报表设计异常及详细日志

##### 截图&代码：

图1

![image](https://user-images.githubusercontent.com/39517907/119290834-e98afa80-bc7f-11eb-9951-dce939e89a0c.png)
图2

![image](https://user-images.githubusercontent.com/39517907/119290852-f0b20880-bc7f-11eb-8941-af291e5a39bc.png)
视图解析出错

图3 预计结果

![image](https://user-images.githubusercontent.com/39517907/119290863-f60f5300-bc7f-11eb-91b6-f80484746960.png)

图4 报表预览

![image](https://user-images.githubusercontent.com/39517907/119290875-fa3b7080-bc7f-11eb-835f-c9f0189dcccc.png)

详细日志

```log
 操作失败，nested exception is org.apache.ibatis.exceptions.PersistenceException: ### Error querying database. Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : SELECT COUNT(*) FROM (select * from (select * from inquirybill_num;) jeecg_rp_temp where 1=1) TOTAL ### The error may exist in URL [jar:file:/C:/Users/PC/.m2/repository/com/jimureport/spring-boot-starter-jimureport/1.1.09-beta/spring-boot-starter-jimureport-1.1.09-beta.jar!/org/jeecg/modules/jmreport/desreport/mapper/xml/JmReportDbMapper.xml] ### The error may involve org.jeecg.modules.jmreport.desreport.mapper.JmReportDbMapper.selectPageBySql ### The error occurred while executing a query ### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : SELECT COUNT(*) FROM (select * from (select * from inquirybill_num;) jeecg_rp_temp where 1=1) TOTAL

```

**Comment by 1298191366** [comment]
已修复，待新版本发布
