### ISSUE TITLE
报表中无法识别html标签

### ISSUE THREAD

**Issue by Leaf-hui** [zhangdaiscott/JimuReport#278]
##### 问题描述：
报表中无法识别html标签，恳请追加此功能。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40714261/119427579-d474a100-bd3d-11eb-9e56-42c1cd143761.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138
