### ISSUE TITLE
1.3.3-beta横向报表不能渲染

### ISSUE THREAD

**Issue by cqangel** [zhangdaiscott/JimuReport#279]
##### 问题描述：
把各个属性设置为横向分组之后，预览报表，没有成功渲染设置的field

##### 截图&代码：

![image](https://user-images.githubusercontent.com/34904026/119434512-e9a3fc80-bd4a-11eb-970b-83519bcec2b2.png)

![image](https://user-images.githubusercontent.com/34904026/119434637-2b34a780-bd4b-11eb-99ff-7228e6b9ae6d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
按照文档配置 https://www.kancloud.cn/zhangdaiscott/jimureport/2250463

**Comment by hexq** [comment]
**版本号：**1.3.4-beta
参考官方文档：http://report.jeecg.com/2119057
**问题描述：**
把省份(province)属性设置为横向分组之后，预览报表，没有成功渲染设置的field，都显示为province。截图见下面，急！！！

**截图&代码：**
1，配置截图
![image](https://user-images.githubusercontent.com/1995173/120631854-ea4f3800-c49a-11eb-9518-3165df433de0.png)

2，预览效果：
![image](https://user-images.githubusercontent.com/1995173/120631906-f9ce8100-c49a-11eb-881e-2b3cc1f7df2d.png)


**JSON数据源：**
{"data":[
    {
        "month":"2021-05",
        "province":"河北",
        "count_type":1,
        "count_1":500,
        "device_type":"T10"
    },
    {
        "month":"2021-04",
        "province":"河北",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-01",
        "province":"河北",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-05",
        "province":"河北",
        "count_type":1,
        "count_1":200,
        "device_type":"T11"
    },
     {
        "month":"2021-04",
        "province":"河北",
        "count_type":1,
        "count_1":0,
        "device_type":"T11"
    },
     {
        "month":"2021-01",
        "province":"河北",
        "count_type":1,
        "count_1":400,
        "device_type":"T11"
    },
    {
        "month":"2021-05",
        "province":"山东",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-04",
        "province":"山东",
        "count_type":1,
        "count_1":500,
        "device_type":"T10"
    },
   {
        "month":"2021-01",
        "province":"山东",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-05",
        "province":"山东",
        "count_type":1,
        "count_1":420,
        "device_type":"T11"
    },
    {
        "month":"2021-04",
        "province":"山东",
        "count_type":1,
        "count_1":400,
        "device_type":"T11"
    },
    {
        "month":"2021-01",
        "province":"山东",
        "count_type":1,
        "count_1":0,
        "device_type":"T11"
    },
    {
        "month":"2021-05",
        "province":"湖南",
        "count_type":1,
        "count_1":0,
        "device_type":"T10"
    },
    {
        "month":"2021-04",
        "province":"湖南",
        "count_type":1,
        "count_1":200,
        "device_type":"T10"
    },
    {
        "month":"2021-01",
        "province":"湖南",
        "count_type":1,
        "count_1":1500,
        "device_type":"T10"
    },
    
    {
        "month":"2021-05",
        "province":"湖南",
        "count_type":1,
        "count_1":0,
        "device_type":"T11"
    },
   
    {
        "month":"2021-04",
        "province":"湖南",
        "count_type":1,
        "count_1":0,
        "device_type":"T11"
    },
    {
        "month":"2021-01",
        "province":"湖南",
        "count_type":1,
        "count_1":1500,
        "device_type":"T11"
    }
]}
