### ISSUE TITLE
地图组件选择北京市页面的标题显示海南省

### ISSUE THREAD

**Issue by macbless** [zhangdaiscott/JimuReport#28]

**Comment by mini2014** [comment]
1、如果你是线上的，现在应该可以，你再试一下
2、如果你是线下的，请升级一下，最新版的没问题

**Comment by macbless** [comment]
收到谢谢
















在 2020-12-10 19:16:47，"mini2014" <notifications@github.com> 写道：

1、如果你是线上的，现在应该可以，你再试一下
2、如果你是线下的，请升级一下，最新版的没问题
