### ISSUE TITLE
多表关联带参数查询,解析出错,无法使用

### ISSUE THREAD

**Issue by jingyingqun1** [zhangdaiscott/JimuReport#281]
##### 问题描述：
      创建数据集，选择好数据源，写了sql语句,在mysql中正常执行，但是在积木报表解析时报错.

##### 截图&代码：
    1.SQL语句:
          select i.template_id  as templateId,i.id as id
          ,i.content as content,i.create_time as ctime,i.end_time as etime,
          d.equip_id as equipId,e.equip_name as ename
          ,p.param_id as paramId,m.param_name as pname,p.check_value as checkValue,
          case when p.param_id like '%_IF%' and p.check_value='0' then '异常'
          when  p.param_id like '%_IF%' and p.check_value='1' then '正常'
          else p.check_value end as vals
          from insp_task_info  i 
          left join insp_task_detail d 
          on i.id=d.task_id 
          left join equip_info e 
          on e.id=d.equip_id
          left join insp_task_param p 
          on p.task_id=i.id
          left join equip_param m 
          on m.id=p.param_id
          where i.template_id='${templateId}'
          and i.create_time>='${ctime}'
          and i.create_time<='${etime}'
   2.积木报表中解析报错如下：
          
![image](https://user-images.githubusercontent.com/70041058/119617050-f4868c00-be33-11eb-9f77-bd755ab06ba0.png)
       
         

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
待测 ws

**Comment by 1298191366** [comment]
测试未发现该问题，你数据源是什么，或更新到最新版本尝试,注意配置私服
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.3-beta</version>
</dependency>
```
![image](https://user-images.githubusercontent.com/30997828/120161672-29c31d80-c22a-11eb-9bfc-4eb3b56b68ab.png)
