### ISSUE TITLE
查询栏条件设置后，列排序失效

### ISSUE THREAD

**Issue by sunkingxie** [zhangdaiscott/JimuReport#282]
##### 问题描述：
报表设计-SQL数据集：
1. SQL文中包含      order by 月份
2. 动态报表配置明细 中    将另外一个字段“国家”设为查询
预览结果：
1. 不设置“国家”查询条件时，排序正常
2. 查询栏条件“国家”设置后，“月份”的排序乱了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/10137498/119639545-4afec500-be4a-11eb-8942-2e07f942d8ee.png)
![image](https://user-images.githubusercontent.com/10137498/119639722-771a4600-be4a-11eb-9eb6-47216fc901c0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
待测 ws

**Comment by 1298191366** [comment]
问题未测出，可否提供数据
![image](https://user-images.githubusercontent.com/30997828/120415122-9a367f80-c38d-11eb-8e95-c70b5a1dcc07.png)
