### ISSUE TITLE
jimu1.2.0版本导出excel有问题

### ISSUE THREAD

**Issue by jingyingqun1** [zhangdaiscott/JimuReport#284]
版本号:1.2.0

问题描述：导出excel出错（集成的是jimu1.2.0版本，pdf导出没有问题，打印也没问题，就是excel导出报错如下）

 截图&代码：

![image](https://user-images.githubusercontent.com/70041058/119772636-17777580-bef2-11eb-8673-b29cad76b15e.png)

![image](https://user-images.githubusercontent.com/70041058/119772908-7937df80-bef2-11eb-9e8e-1ed215393fb2.png)

![image](https://user-images.githubusercontent.com/70041058/119772931-7fc65700-bef2-11eb-887a-f09d32751480.png)

**Comment by zhangdaiscott** [comment]
你这个是poi版本冲突

**Comment by jingyingqun1** [comment]
那应该需要哪个版本的？
