### ISSUE TITLE
打印字迹，模糊

### ISSUE THREAD

**Issue by baohaolong6666** [zhangdaiscott/JimuReport#286]
##### 版本号：
1.3.21-beta

##### 问题描述：
打印出来，一个字迹有些笔画有些模糊。用其他地方打印没问题，从网友预览打印出现字迹模糊。打印机是没问题。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
能附图吗

**Comment by baohaolong6666** [comment]
已找到原因。打印设置清晰度为6即可

**Comment by tygithub1** [comment]
原来的打印的是图片，会有模糊的情况，已经在做原生html 的打印了，以后不需要设置清晰度也能清晰打印
