### ISSUE TITLE
积木图形报表没有定时刷新数据功能

### ISSUE THREAD

**Issue by lwy2016** [zhangdaiscott/JimuReport#287]
##### 版本号：
1.3.21-beta

##### 问题描述：
在积木图形报表中，图表是有定时刷新功能的，但是对于普通的SQL数据查询没有定时刷新的功能，大佬能否安排此项功能列入开发计划。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/5600533/119941939-d2237880-bfc3-11eb-86af-ac5a421a222c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
无计划
