### ISSUE TITLE
优化：数据报表增加行级间颜色变化设置选项

### ISSUE THREAD

**Issue by Teng888Teng** [zhangdaiscott/JimuReport#288]
##### 版本号：
1.3.3

##### 问题描述：
    数据报表行级没有颜色区分，可以增加该功能

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
是斑马线的功能？

**Comment by Teng888Teng** [comment]
是的

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138

**Comment by ananasman** [comment]
循环单元格格式调整下就有了
=(let no= #{data.pagehelper_row_id};
 if(no%2==1){
     rowcolor('#{data.value}','black','#ffffff')
}else{
     rowcolor('#{data.value}','black','#d8d8d8')
})
