### ISSUE TITLE
api分页有问题。总页数显示错误

### ISSUE THREAD

**Issue by iojyggfhkkluygv** [zhangdaiscott/JimuReport#289]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/50935022/119963949-43225a80-bfdb-11eb-9823-cb0d74f874fa.png)

![image](https://user-images.githubusercontent.com/50935022/119963975-47e70e80-bfdb-11eb-9653-149c719f677e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by iojyggfhkkluygv** [comment]
是不是我哪里配置错误呢

**Comment by 1298191366** [comment]
目前是total是总页数就是13的那个，count是总条数。

**Comment by 1298191366** [comment]
或者可以用[api接口数据格式适配](http://report.jeecg.com/2159713)进行转换一下

**Comment by zizihrhr335500** [comment]
> 目前是total是总页数就是13的那个，count是总条数。

那pages 又是啥。。。

**Comment by 1298191366** [comment]
> > 目前是total是总页数就是13的那个，count是总条数。
> 
> 那pages 又是啥。。。

你从哪里来看的有pages?一共就两个属性，一个是total,一个是count

**Comment by zizihrhr335500** [comment]
> > > 目前是total是总页数就是13的那个，count是总条数。
> > 
> > 
> > 那pages 又是啥。。。
> 
> 你从哪里看的有pages?一共就两个属性，一个是total,一个是count

![image](https://user-images.githubusercontent.com/35367427/120467252-91b46800-c3d2-11eb-9f43-3b6567a23dcb.png)

![image](https://user-images.githubusercontent.com/35367427/120467158-747f9980-c3d2-11eb-9d1c-df528dd94957.png)

![image](https://user-images.githubusercontent.com/35367427/120467209-819c8880-c3d2-11eb-82bb-0ccd7e4ec822.png)

实现IDataSetFactory 接口后 JmPage对象中的 pages.

**Comment by iojyggfhkkluygv** [comment]
![Uploading image.png…]()

**Comment by iojyggfhkkluygv** [comment]
![image](https://user-images.githubusercontent.com/50935022/120468276-9fb6b880-c3d3-11eb-8af7-f5e395718c10.png)

**Comment by 1298191366** [comment]
> > > > 目前是total是总页数就是13的那个，count是总条数。
> > > 
> > > 
> > > 那pages 又是啥。。。
> > 
> > 
> > 你从哪里看的有pages?一共就两个属性，一个是total,一个是count
> 
> ![image](https://user-images.githubusercontent.com/35367427/120467252-91b46800-c3d2-11eb-9f43-3b6567a23dcb.png)
> 
> ![image](https://user-images.githubusercontent.com/35367427/120467158-747f9980-c3d2-11eb-9d1c-df528dd94957.png)
> 
> ![image](https://user-images.githubusercontent.com/35367427/120467209-819c8880-c3d2-11eb-82bb-0ccd7e4ec822.png)
> 
> 实现IDataSetFactory 接口后 JmPage对象中的 pages.

了解，你只需要设置这三个参数即可，pageSize是每页显示记录数
![image](https://user-images.githubusercontent.com/30997828/120468030-5d8d7700-c3d3-11eb-812f-b7d43b7a27df.png)

**Comment by zizihrhr335500** [comment]
> > > > > 目前是total是总页数就是13的那个，count是总条数。
> > > > 
> > > > 
> > > > 那pages 又是啥。。。
> > > 
> > > 
> > > 你从哪里看的有pages?一共就两个属性，一个是total,一个是count
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/35367427/120467252-91b46800-c3d2-11eb-9f43-3b6567a23dcb.png)
> > ![image](https://user-images.githubusercontent.com/35367427/120467158-747f9980-c3d2-11eb-9d1c-df528dd94957.png)
> > ![image](https://user-images.githubusercontent.com/35367427/120467209-819c8880-c3d2-11eb-82bb-0ccd7e4ec822.png)
> > 实现IDataSetFactory 接口后 JmPage对象中的 pages.
> 
> 了解，你只需要设置这三个参数即可，pageSize是每页显示记录数
> ![image](https://user-images.githubusercontent.com/30997828/120468030-5d8d7700-c3d3-11eb-812f-b7d43b7a27df.png)

可以理解为，目前版本就把total当作页数，pages先不管了这样是吧

**Comment by iojyggfhkkluygv** [comment]
![Uploading image.png…]()

**Comment by 1298191366** [comment]
pages下面自动计算的

**Comment by zizihrhr335500** [comment]
> pages下面自动计算的

bean的这种方式也会有楼主的问题。也是页数取的total ，total设置啥，页面的总页数显示啥

**Comment by iojyggfhkkluygv** [comment]
![image](https://user-images.githubusercontent.com/50935022/120469106-86fad280-c3d4-11eb-8020-1867a0f0d088.png)

![image](https://user-images.githubusercontent.com/50935022/120469043-75192f80-c3d4-11eb-9f29-7f5d293fb622.png)

**Comment by 1298191366** [comment]
收录，例子是之前写的，文档会处理，感谢提醒
