### ISSUE TITLE
首页分页问题

### ISSUE THREAD

**Issue by zsjvtm** [zhangdaiscott/JimuReport#291]
版本号：1.3.3

问题描述：
报表显示分页有问题，显示总共有14个报表，点击第一页看不到报表，另外设计分页条数无效

##### 截图&代码：

![image](https://user-images.githubusercontent.com/22512787/120128214-14cb9780-c1f4-11eb-88b9-8ddf171b1f4e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
