### ISSUE TITLE
导出excel一直处于加载中，并且CPU暴涨

### ISSUE THREAD

**Issue by leazxl** [zhangdaiscott/JimuReport#292]
##### 版本号：
1.3.3

##### 问题描述：
1、sql数据量大的时候，导出excel一直处于加载中，并且CPU暴涨

##### 截图&代码：
![image](https://user-images.githubusercontent.com/460279/120137866-d63fd800-c207-11eb-93a8-46a82eb3f88e.png)
![image](https://user-images.githubusercontent.com/460279/120137907-e8ba1180-c207-11eb-8af2-97c04f721279.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级这个版本试试，注意配置jeecg Maven私服

```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.4-beta</version>
</dependency>
```

**Comment by leazxl** [comment]
> 升级这个版本试试，注意配置jeecg Maven私服
> 
> ```
> <dependency>
>     <groupId>org.jeecgframework.jimureport</groupId>
>     <artifactId>spring-boot-starter-jimureport</artifactId>
>     <version>1.3.4-beta</version>
> </dependency>
> ```

这个版本数据库文件有改变，有没有数据库升级文件？

**Comment by zhangdaiscott** [comment]
http://jimureport.com/doc/log
