### ISSUE TITLE
表格中存在负数，合计的时候，设置两位小数不起作用，而且数据不正确

### ISSUE THREAD

**Issue by aixiaodenvhai** [zhangdaiscott/JimuReport#293]
##### 版本号：
1.3.3-beta

##### 问题描述：
表格中遇到有负数累加的结果，设置两位小数不起作用

##### 截图&代码：

![image](https://user-images.githubusercontent.com/12838589/120147478-4c006f80-c219-11eb-8742-f98d7a048173.png)

![image](https://user-images.githubusercontent.com/12838589/120147523-5e7aa900-c219-11eb-9258-7932d8dd8236.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
负数问题已修复，下个版本发布，另外，小数点生效的前提是，该单元格需设置成数值格式
