### ISSUE TITLE
api数据源带参，报空指针

### ISSUE THREAD

**Issue by baohaolong6666** [zhangdaiscott/JimuReport#294]
##### 版本号：

1.3.21-beta
##### 问题描述：
预览路径带有参数值：
http://localhost:8085/jmreport/view/557464769126170624?reportId=557464769126170624
配置了参数：
![image](https://user-images.githubusercontent.com/47874532/120151713-2e360900-c21f-11eb-822c-f9c17b93d707.png)
但是后台报错：
一直获取不到reportId的值
![image](https://user-images.githubusercontent.com/47874532/120151792-46a62380-c21f-11eb-96b1-51f66a977a32.png)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
请使用最新版:
`<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.4-beta</version>
</dependency>`
