### ISSUE TITLE
交叉分组横向求和

### ISSUE THREAD

**Issue by GeniyGOD** [zhangdaiscott/JimuReport#295]
##### 版本号：
1.3.3-beta

##### 问题描述：
不太清楚交叉报表的横向求和（C4单元格）和总计（C5单元格）如何操作，麻烦告知一下。

这是想要达到的效果
![KU`Y3KD9Q J7 WSJ0M3EJH9](https://user-images.githubusercontent.com/33958122/120166762-87a63400-c22f-11eb-8b3f-2286d29177c6.png)

这是设计器中的
![JC3Z_8D7D3LG0B@KD 8H )0](https://user-images.githubusercontent.com/33958122/120165978-b4a61700-c22e-11eb-8b08-99e3571ed510.jpg)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138

**Comment by zhangdaiscott** [comment]
计算方式可写成：`#{tt.dynamic(sales+gift)}`， 支持加减乘除
