### ISSUE TITLE
负数相加的和不对

### ISSUE THREAD

**Issue by aixiaodenvhai** [zhangdaiscott/JimuReport#297]
##### 版本号：
1.3.3-beta

##### 问题描述：

负数sum统计的和不对的问题
##### 截图&代码：

![image](https://user-images.githubusercontent.com/12838589/120579338-ec44d700-c459-11eb-9f5f-5bcb172c1c60.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级到最新版本
http://jimureport.com/doc/log
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.51-beta</version>
</dependency>
```
