### ISSUE TITLE
无法实现不循环与循环共存

### ISSUE THREAD

**Issue by baohaolong6666** [zhangdaiscott/JimuReport#299]
##### 版本号：

1.3.21-beta
##### 问题描述：

标题应该只显示一个，但是显示了多个
##### 截图&代码：

![image](https://user-images.githubusercontent.com/47874532/120621030-1d3ffe80-c490-11eb-9447-89292f57c932.png)

![image](https://user-images.githubusercontent.com/47874532/120621080-28932a00-c490-11eb-8629-98b2f83d402e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
https://www.kancloud.cn/zhangdaiscott/jimureport/2233183
https://www.kancloud.cn/zhangdaiscott/jimureport/2233184
数据集区分 ：是否列表

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138
