### ISSUE TITLE
这个积木报表, 会单独拿出来开源吗

### ISSUE THREAD

**Issue by nuan1989** [zhangdaiscott/JimuReport#3]
这个积木报表, 会单独拿出来开源吗

**Comment by MyEclipseyang** [comment]
> 
> 
> 这个积木报表, 会单独拿出来开源吗

可以了解一下开源的Davinci，也能实现大屏和报表

**Comment by copyshop** [comment]
什么时候会开源，最近正好需要实现一个套打功能，可能会用到。

**Comment by copyshop** [comment]
> 这个积木报表, 会单独拿出来开源吗

可以先查看ureport2 看看能不能满足你们的功能。

**Comment by zhangdaiscott** [comment]
集成版本已经开放
