### ISSUE TITLE
报表预览页面不能复制文本

### ISSUE THREAD

**Issue by tyhg001** [zhangdaiscott/JimuReport#301]
##### 截图&代码：报表预览页面不能复制文本
![image](https://user-images.githubusercontent.com/19584941/120735698-ab15fb00-c51d-11eb-8f70-4c37ec45035b.png)
这里面文字都只能看，不是复制，在反查相关信息时极不方便

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持
