### ISSUE TITLE
版本号：1.3.4-beta 超链接 新打开窗口 返回上一页 按钮能不能不显示

### ISSUE THREAD

**Issue by aixiaodenvhai** [zhangdaiscott/JimuReport#302]
##### 版本号：

1.3.4-beta 
##### 问题描述：
超链接 新打开窗口 返回上一页 按钮能不能不显示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12838589/120740349-a1909100-c525-11eb-860f-e3ff1473eb24.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by tygithub1** [comment]
已修复，下个版本发布

**Comment by aixiaodenvhai** [comment]
好的，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月11日(星期五) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaiscott/JimuReport] 版本号：1.3.4-beta 超链接 新打开窗口 返回上一页 按钮能不能不显示 (#302)





 
已修复，下个版本发布
