### ISSUE TITLE
如何批量打印报表分页？

### ISSUE THREAD

**Issue by LY-CS** [zhangdaiscott/JimuReport#303]
##### 版本号：
1.3.3-beta

##### 问题描述：
报表分页之后，如何批量打印所有页面结果

##### 截图&代码：
分页的样式，总共四页
![image](https://user-images.githubusercontent.com/49343378/120774839-41194800-c555-11eb-8e60-57505e190435.png)

想要批量把四页按现在样式打印下来。现在只有打印全部，如下图，分页样式都没有了。
![image](https://user-images.githubusercontent.com/49343378/120775350-b422be80-c555-11eb-91ed-296b09572024.png)

这个有什么设置可以调吗？

最后谢谢各位开发人员给我们提供这么优秀的报表框架。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #138
