### ISSUE TITLE
使用多数据对比柱状图时，如果查询条件后图表重叠

### ISSUE THREAD

**Issue by xinxingzhao** [zhangdaiscott/JimuReport#305]
##### 版本号：

1.3.4-beta

##### 问题描述：

使用多数据对比柱状图时，如果输入条件查询，图表会出现重叠

##### 截图&代码：

进入报表初始状态：
![image](https://user-images.githubusercontent.com/13712791/120917636-e01f7a80-c6e2-11eb-854d-2580d5271ea3.png)

输入条件查询之后
![image](https://user-images.githubusercontent.com/13712791/120917661-0513ed80-c6e3-11eb-99be-0668b236a08c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by xinxingzhao** [comment]
@zhangdaiscott 这是一个bug？收录 ws 是指什么？

**Comment by 1298191366** [comment]
已修复，待新版本发布
