### ISSUE TITLE
是否能提供Oracle建表SQL语句脚本???

### ISSUE THREAD

**Issue by jueding920** [zhangdaiscott/JimuReport#311]
##### 版本号：
1.3.4-beta

##### 问题描述：
是否能提供Oracle建表SQL语句脚本，通过官方mysql转Oracle方法转换表测试老不成功！

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/4905722
