### ISSUE TITLE
关于电子表格滚动条问题

### ISSUE THREAD

**Issue by weenhall** [zhangdaiscott/JimuReport#312]
##### 问题描述：
电子表格只有横向滚动条，垂直滚动条无法出来

##### 截图&代码：

![image](https://user-images.githubusercontent.com/12906841/121163443-5ce85b00-c881-11eb-9108-48ab4b65eac6.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
遮挡右侧的操作栏就可以出来了
