### ISSUE TITLE
组件复制功能

### ISSUE THREAD

**Issue by caiiansheng** [zhangdaiscott/JimuReport#315]
##### 版本号：
所有版本

##### 问题描述：
1. 设计界面的组件 没有复制功能，因为设计完一个图表，各种样式都配置好了，再创建一个图表还得重新配置样式，所以需要提供组件复制的功能。
2. 能不能提供卡片组件

##### 截图&代码：
卡片：
![image](https://user-images.githubusercontent.com/26760483/121333966-d9477080-c94b-11eb-9d86-9a12014fa9d2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
不支持
