### ISSUE TITLE
预览和设计加载外网js  ,加载慢

### ISSUE THREAD

**Issue by caiiansheng** [zhangdaiscott/JimuReport#316]
##### 版本号：
1.3.3-beta

##### 问题描述：
报表预览和设计的时候，JS会加载 百度的两个js 文件，如果网络不好或者网络不通，会等待好长时间才加载出来

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26760483/121335223-fa5c9100-c94c-11eb-8b2c-24b948a63191.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 scott

**Comment by zhangdaiscott** [comment]
修复了，下个版本发布
