### ISSUE TITLE
非jeecg-boot项目集成积木报表，在上传背景图片时，请求头中没有加上token，是否可以加上？

### ISSUE THREAD

**Issue by lusl1991** [zhangdaiscott/JimuReport#318]
##### 截图&代码：
![bg](https://user-images.githubusercontent.com/28939880/121479362-87aaee80-c9fc-11eb-9f24-f1013b12d710.png)
![api](https://user-images.githubusercontent.com/28939880/121479382-8c6fa280-c9fc-11eb-96b9-4b7e18978404.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改
