### ISSUE TITLE
报表设计器功能优化

### ISSUE THREAD

**Issue by mojiezsy** [zhangdaiscott/JimuReport#321]
##### 版本号：
1.3.4-beta

##### 问题描述：
进行页面设计时，无法精准的设计列、行的大小。
例如A、B两列要宽度一样，只能用拖拽的方式设置宽度，无法精确。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/83196014/121627926-de6f0180-caaa-11eb-8f39-ec2bae07a573.png)

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by tygithub1** [comment]
已修改
