### ISSUE TITLE
积木报表的文档无法搜索

### ISSUE THREAD

**Issue by xinxingzhao** [zhangdaiscott/JimuReport#323]
##### 版本号：

1.3.2

##### 问题描述：

积木报表的文档无法搜索

##### 截图&代码：

![image](https://user-images.githubusercontent.com/13712791/121711332-13ac3b80-cb0d-11eb-8803-e223d26d21d2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
好了
