### ISSUE TITLE
图形报表条件搜索时图层数据错乱问题

### ISSUE THREAD

**Issue by pqf773** [zhangdaiscott/JimuReport#325]
##### 版本号：
1.3.5-beta

##### 问题描述：
图形报表（已知柱状&饼状）根据条件搜索时当前图表未重置，新数据渲染时造成图层叠加错乱

##### 截图&代码：
![image](https://user-images.githubusercontent.com/18442759/122185340-9b07ff00-cebf-11eb-9e16-902e58a66313.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
这个问题已经修复了，新版本发布

**Comment by xinxingzhao** [comment]
https://github.com/zhangdaiscott/JimuReport/issues/323
