### ISSUE TITLE
导出是否可以支持Word格式

### ISSUE THREAD

**Issue by mojiezsy** [zhangdaiscott/JimuReport#327]
##### 版本号：
1.3.4-beta

##### 问题描述：
一些报告相关的内容需要用到word，是否可以考虑支持导出word格式文件

##### 截图&代码：

![image](https://user-images.githubusercontent.com/83196014/122341290-e4b32100-cf75-11eb-90ff-adec778a3f6b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by EvilMir** [comment]
我现在用的时候是导出excel之后，直接复制到word,然后选中表格做个 表格调整-根据内容自动调整
不过还是需要微调一下。

**Comment by zhangdaiscott** [comment]
未计划支持
