### ISSUE TITLE
没有基于jeecg-boot的项目,引入404

### ISSUE THREAD

**Issue by zhangglCoder** [zhangdaiscott/JimuReport#33]
```
<dependency>
            <groupId>com.jimureport</groupId>
            <artifactId>spring-boot-starter-jimureport</artifactId>
            <version>1.1-beta</version>
        </dependency>
```

![image](https://user-images.githubusercontent.com/7490542/101447561-6b040000-3960-11eb-8d1b-abf165d875c7.png)

![image](https://user-images.githubusercontent.com/7490542/101447775-d9e15900-3960-11eb-8f27-2298881e627c.png)

![image](https://user-images.githubusercontent.com/7490542/101456671-609d3280-396f-11eb-993c-51116e6da61f.png)
搭建过程中遇到的问题，本地Maven仓库是可以拉到Jar包的，但是Class 没办法加载进来

**Comment by zhangdaiscott** [comment]
加下扫码路径 "org.jeecg"

**Comment by zhangglCoder** [comment]
![image](https://user-images.githubusercontent.com/7490542/101456531-29c71c80-396f-11eb-8da4-64c53389c50c.png)

搭建过程中遇到的问题，本地Maven仓库是可以拉到Jar包的，但是Class 没办法加载进来

**Comment by buerbl** [comment]
能否与Spring集成呢

**Comment by Scroogeds** [comment]
你好，有解决嘛，请求报404

**Comment by g1335333249** [comment]
> 你好，有解决嘛，请求报404

请问解决了嘛

**Comment by accpman** [comment]
下一步会出一个单独跟springboot集成的项目

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/4779874

#####  #常见问题

###### 1.  访问菜单404
![](https://oscimg.oschina.net/oscnet/up-078896fe307427db11c9bd3b8aa886a7606.png)

解决方法：

-  a.添加新依赖请刷新依赖，不刷新依赖不生效
![](https://oscimg.oschina.net/oscnet/up-c739293dc312c2b5bdd0b4f2602d21367f0.png)

-  b.版本更新重构过菜单的请求地址
    所以如果你引用低于1.1版本的依赖，请参考[1.0文档](https://my.oschina.net/jeecg/blog/4694834) 修改菜单地址

###### 2.  非jeecgboot项目集成缺少依赖
![](https://oscimg.oschina.net/oscnet/up-0db41178195946bf69d1cbfceea8ebd2ad7.png)

解决方法： 加入下面动态数据源依赖

```
<!-- 动态数据源 -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.1.17</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>
        <!-- AutoPoi Excel-->
        <dependency>
            <groupId>org.jeecgframework</groupId>
            <artifactId>autopoi-web</artifactId>
            <version>1.2.2</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-codec</groupId>
                    <artifactId>commons-codec</artifactId>
                </exclusion>
            </exclusions>
            <optional>true</optional>
        </dependency>
```
