### ISSUE TITLE
请问报表如何添加行号?

### ISSUE THREAD

**Issue by jsonzoup** [zhangdaiscott/JimuReport#330]
##### 版本号：
1.3.4.beta

##### 问题描述：
请问报表如何添加行号?

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经修复，升级到版本1.3.63-beta , 要[配置私服](http://report.jeecg.com/2195924)

文档：http://report.jeecg.com/2332220
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.3.63-beta</version>
</dependency>
```
