### ISSUE TITLE
sql使用where条件的时候，空指针异常

### ISSUE THREAD

**Issue by newbeexb** [zhangdaiscott/JimuReport#334]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18304205/123020014-30e1e380-d404-11eb-8fc4-84d806400089.png)
![image](https://user-images.githubusercontent.com/18304205/123020127-5e2e9180-d404-11eb-885e-0bc155c7a398.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级到
1.3.51-beta
