### ISSUE TITLE
是否支持主子表？

### ISSUE THREAD

**Issue by quebecmcj** [zhangdaiscott/JimuReport#34]
有以下场景，有一个工程(主表)，有供应商信息(子表)，有材料信息(子表)，报表上面显示工程信息(一条数据但是分多行显示)，下面显示供应商信息(多条数据多行显示，每行显示一条数据)，再下面显示材料信息(多条数据多行显示，每行显示一条数据)，这种主子表形式的报表是否可以支持？

**Comment by mini2014** [comment]
暂时不支持！
我们正在研发，下个版本会支持

**Comment by tianchenglong323** [comment]
> 暂时不支持！
> 我们正在研发，下个版本会支持。
> 你可以把你要做成什么样子的图片放在这里，谢谢！

主子表用到的场景特别多   下个版本大概什么时候发布呢

**Comment by zhangdaiscott** [comment]
多数据源不就可以了

**Comment by mini2014** [comment]
> > 暂时不支持！
> > 我们正在研发，下个版本会支持。
> > 你可以把你要做成什么样子的图片放在这里，谢谢！
> 
> 主子表用到的场景特别多 下个版本大概什么时候发布呢

下个版本下个月会发布

**Comment by zhangdaiscott** [comment]
类似问题 https://github.com/zhangdaiscott/JimuReport/issues/67

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/4990947
