### ISSUE TITLE
积木报表api参数问题

### ISSUE THREAD

**Issue by iwen-git** [zhangdaiscott/JimuReport#37]
![Q2@ 8M2DW)J63(__}K0%L](https://user-images.githubusercontent.com/32193518/102051826-2248bd00-3e20-11eb-9469-f5189e66d0b2.png)

![G2UT8%$95_`8KL_KVH@ZOAQ](https://user-images.githubusercontent.com/32193518/102051834-24ab1700-3e20-11eb-99f1-056ad711f278.png)

![94NL83ORUKJVS{ ~ NE{A$4](https://user-images.githubusercontent.com/32193518/102051845-270d7100-3e20-11eb-8cb4-be9de5311a04.png)

![QOC(JK81`TV4NP{9RBCVAOT](https://user-images.githubusercontent.com/32193518/102051865-2ecd1580-3e20-11eb-9608-83af894cc85d.png)

后台参数解析出来是个空的，怎么能接收到数据呢，是配置的不对吗

**Comment by zhangdaiscott** [comment]
用法不对，查询条件是自动生成sql，只支持sql模式。
传递参数用法参考文档
http://report.jeecg.com/1877428
