### ISSUE TITLE
地图组件-完整的省级区划地图什么时候提供

### ISSUE THREAD

**Issue by wzwgithubw** [zhangdaiscott/JimuReport#38]
请问一下哈，目前地图组件中可选择的省份地图太少，什么时候能够提供湖南省的地图组件哦？
![image](https://user-images.githubusercontent.com/14305359/102190708-5214c500-3ef3-11eb-9090-19854584afa8.png)

**Comment by mini2014** [comment]
下周，我们会发布线上可以自己添加地图地区，到时候可以添加自己使用的地区

**Comment by wzwgithubw** [comment]
作者好，地图组件升级了没，二十多天啦？

**Comment by wzwgithubw** [comment]
@mini2014
