### ISSUE TITLE
前端新建报表时报token非法的问题

### ISSUE THREAD

**Issue by MDWizard** [zhangdaiscott/JimuReport#40]
跟进昨天在群里说的问题，新建报表时出现
 出现token非法的情况。
目前分析如下：
前台在点击新建报表时，先调用的save方法
 //新建报表
            createExcel: function(){
                var that = this;
                $http.post({
                    url:api.saveReport,
                    data:{},
                    contentType:'json',
                    success:(result)=>{
                        window.open(api.index+result.id+"?token="+this.token);
                    }
                },that)
            },
后台进入方法

@PostMapping({"/save"})
    @JimuLoginRequired
    public Result<?> a(HttpServletRequest var1, @RequestBody JSONObject var2) {
        try {
            JimuReport var3 = this.jmReportDesignService.saveReport(var2);
            return Result.OK(var3);
        } catch (Exception var4) {
            return Result.error(403, "token非法");
        }
    }

public JimuReport saveReport(JSONObject json) {
        String var2 = this.jimuTokenClient.getUsername(this.request);
        a.debug("============EXCEL JSON数据正在保存==========");
        String var3 = json.getString("excel_config_id");
        LambdaQueryWrapper var4 = new LambdaQueryWrapper();
        var4.eq(JimuReport::getId, var3);
        JimuReport var5 = (JimuReport)((JimuReportMapper)this.baseMapper).selectOne(var4);
        JSONObject var6 = json.getJSONObject("designerObj");
        String var7 = "";
        String var8 = "";
        if (var6 != null) {
            var7 = var6.getString("name");
            var8 = var6.getString("type");
            json.remove("designerObj");
        }
......

调用save时，代码会从前端传参中获取报表的主键，并调用selectOne方法，但由于新建时，无该主键，所以selectOne抛出异常，该异常被上层捕获后，直接抛出token非法的错误，最终导致该问题。我个人觉得这是一个前端逻辑bug，新建时为什么要save？

**Comment by 1298191366** [comment]
未发现该问题，解释1、selectOne是因为查看随机生成的id是否重复。2、抛出异常只能是存在多条数据id（理论上不可能），请删除数据重试。3、如果还存在问题，请按照文档重试

**Comment by lucifa7** [comment]
遇到相同问题

**Comment by mini2014** [comment]
@lucifa7 你也按上边 @1298191366 的方法试一下
