### ISSUE TITLE
大屏尺寸不兼容1920x1080

### ISSUE THREAD

**Issue by rx520** [zhangdaiscott/JimuReport#42]
@zhangdaiscott 
![1608287431(1)](https://user-images.githubusercontent.com/67148645/102604623-652bcd00-415f-11eb-81ca-20a11cdf7b2c.jpg)
![1608287494(1)](https://user-images.githubusercontent.com/67148645/102604631-6bba4480-415f-11eb-80aa-5f7a7a91cafb.jpg)
在大屏设计器中设置大屏尺寸 1920x1080 在实际使用中全屏观看的时候,出现了滚动条,并且滚到到最右边会出现一块黑色的边,详情见如上图

**Comment by zhangdaiscott** [comment]
已经改了，请确认

**Comment by mini2014** [comment]
这个功能已修改
