### ISSUE TITLE
sql解析出错

### ISSUE THREAD

**Issue by uuc33** [zhangdaiscott/JimuReport#53]
我有一个sql  类似于
select a,b,c from db1
union 
select * from (
select a2,b1,c1 from db2
where ....
group by ...)db3
这种，但是sql解析的时候会把where及其之后的内容截断，变成
select count(1) from (select a,b,c from db1
union 
select a2,b1,c1 from db2) temp_count where 1=1  这种了，有办法解决吗

**Comment by uuc33** [comment]
F12看传参，应该是前端给截取错了

**Comment by uuc33** [comment]
sql:
select tmp1.busDeptName as '中心',count(tmp1.emplId) as '中心总人数',
  tmp3.courseNum as '应学课程数据',
sum(if(tmp2.isLook>0,1,0)) as '参与人数',
sum(if(tmp2.totalCnt=courseNum,1,0)) as '完成人数'
from 
(select post.emplId,post.deptId,busDept.busDeptId ,busDeptName
from post  
JOIN (
select CONCAT(deptId,'') deptId,CONCAT(deptId,'') as busDeptId,descr as busDeptName from dept_node dn where setId=10000 and deptId in (1000000027, 1000000028, 1000000031, 1000000033, 1000000118, 1000000124, 1000000138, 1000000164, 1000000174, 1000000179, 1000000184, 1000000185, 1000000186) and effStatus='A'
union all
select CONCAT(deptId,'') deptId,dn.node2 as busDeptId,node2Descr as busDeptName from dept_node dn where setId=10000 and node2 in ('1000000027', '1000000028', '1000000031', '1000000033', '1000000118', '1000000124', '1000000138', '1000000164', '1000000174', '1000000179', '1000000184', '1000000185', '1000000186') and effStatus='A'
union all
select CONCAT(deptId,'') deptId,dn.node3 as busDeptId ,node3Descr as busDeptName from dept_node dn where setId=10000 and node3 in ('1000000027', '1000000028', '1000000031', '1000000033', '1000000118', '1000000124', '1000000138', '1000000164', '1000000174', '1000000179', '1000000184', '1000000185', '1000000186') and effStatus='A'
union all
select CONCAT(deptId,'')deptId,dn.node4 as busDeptId,node4Descr as busDeptName  from dept_node dn where setId=10000 and node4 in ('1000000027', '1000000028', '1000000031', '1000000033', '1000000118', '1000000124', '1000000138', '1000000164', '1000000174', '1000000179', '1000000184', '1000000185', '1000000186') and effStatus='A'
) busDept on  post.deptId=busDept.deptId
where post.setidDept='10000' and hrStatus='A')tmp1
LEFT JOIN 
( select a.emplId,a.emplName,a.setId,a.deptId,
sum(if(a.sectionCount=a.lookCnt,1,0)) totalCnt,
if(a.isLook>0,1,0) isLook
 from 
(
select `user`.id userId,`user`.emplId,`user`.emplName,`user`.setId,user.deptId,
cs.sectionCount,
sum(if(cr.watchFullState=1,1,0)) lookCnt,
sum(if(cr.id is not null,1,0)) isLook
 from
course cs
LEFT JOIN course_record cr on cs.id=cr.courseId and cr.state=1
LEFT JOIN `user` on `user`.id=cr.userId
where cs.id in (select home_label_link.relationId from home_label 
                  LEFT JOIN home_label_link on home_label_link.labelId=home_label.id and home_label_link.state=1
                   where ownCity='10000' and contentType=0)
and `user`.userType=2 and `user`.setId=10000
GROUP BY userid,cs.id) a
GROUP BY a.userId ) tmp2 on tmp1.emplId=CONCAT(tmp2.emplId,'')
LEFT JOIN (select count(1) courseNum from home_label 
LEFT JOIN home_label_link on home_label_link.labelId=home_label.id and home_label_link.state=1
where ownCity='10000' and contentType=0) tmp3 on 1=1
GROUP BY tmp1.busDeptId

后台日志
![image](https://user-images.githubusercontent.com/32947622/103991059-24a6f880-51cd-11eb-9f76-a0223ce964a9.png)
前端传值
![image](https://user-images.githubusercontent.com/32947622/103991124-3c7e7c80-51cd-11eb-84cc-979251d0373e.png)
sql: select tmp1.busDeptName as '中心',count(tmp1.emplId) as '中心总人数',
  tmp3.courseNum as '应学课程数据',
sum(if(tmp2.isLook>0,1,0)) as '参与人数',
sum(if(tmp2.totalCnt=courseNum,1,0)) as '完成人数'
from 
(select post.emplId,post.deptId,busDept.busDeptId ,busDeptName
from post  
JOIN (
select CONCAT(deptId,'') deptId,CONCAT(deptId,'') as busDeptId,descr as busDeptName from dept_node dn

**Comment by zhangdaiscott** [comment]
收录，待分析

**Comment by tygithub1** [comment]
已修复 版本1.1.05++发布

**Comment by uuc33** [comment]
后台也有问题 ，通过where截取数据后sql就有问题了。 比如select * from (select * from b where b.id=123) a

**Comment by uuc33** [comment]
@tygithub1
