### ISSUE TITLE
导出功能无法使用

### ISSUE THREAD

**Issue by seenukwan** [zhangdaiscott/JimuReport#56]
1、带参数api数据集，excel导出，后台只接收到参数默认值，且调式接口有数据返回，但是表格还是${}字段，没有数据替换。参数只接收默认字段应该是下面这段代码的问题， 数据没替换不知道原因
`for(var47 = var45.keySet().iterator(); var47.hasNext(); var21 = var21.replace(var49 + "='${" + var49 + "}'", var49 + "=" + var26)) {
                    var49 = (String)var47.next();
                    var26 = var45.getString(var49);
                    if (StringUtils.isEmpty(var26)) {
                        var26 = "";
                    }
                }`
2、pdf导出也是没有参数传入，麻烦看看原因

**Comment by seenukwan** [comment]
导出Excel时list条数大于一可以显示，小于一的不行

**Comment by seenukwan** [comment]
> 导出Excel时list条数大于一可以显示，小于一的不行

条数等于一时通过字段的中文名字取替换，应该是bug
![image](https://user-images.githubusercontent.com/11736727/103736105-8844f080-502a-11eb-8862-ec6961b61420.png)

**Comment by zhangdaiscott** [comment]
收录

**Comment by mini2014** [comment]
已修复
