### ISSUE TITLE
报表设计器无法新建报表，提示非法token

### ISSUE THREAD

**Issue by aaron52101314** [zhangdaiscott/JimuReport#57]
1. 集成版本
        <dependency>
  	        <groupId>com.jimureport</groupId>
  	        <artifactId>spring-boot-starter-jimureport</artifactId>
  	        <version>1.1.02-beta</version>
        </dependency>

2. 已配置shiro排除

 //积木报表排除
  filterChainDefinitionMap.put("/jmreport/**", "anon");
  filterChainDefinitionMap.put("/**/*.js.map", "anon");
  filterChainDefinitionMap.put("/**/*.css.map", "anon");

3. 报表访问路径：https://localhost:8443/jmreport/list

4. 报表设计器无法新建报表，提示非法token
![image](https://user-images.githubusercontent.com/38207492/103754080-d831b080-5046-11eb-8fe9-5deafe1b481d.png)

5. 覆盖代码JimureportServiceImpl.java，重写verifyToken, 直接return true，还是提示非法token

6. 提示非法token时(https://localhost:8443/jmreport/save)，接口响应：
{"success":false,"message":"token非法","code":403,"result":null,"timestamp":1609926464904}.

**Comment by zhangdaiscott** [comment]
debug JimureportServiceImpl
进入这个方法了吗

**Comment by aaron52101314** [comment]
> debug JimureportServiceImpl
> 进入这个方法了吗
进了JimureportServiceImpl.java的这个public Boolean verifyToken(String token)方法的，直接返回true还是不行。

**Comment by zhangdaiscott** [comment]
JimureportServiceImpl 代码贴出来看看

**Comment by aaron52101314** [comment]
> JimureportServiceImpl 代码贴出来看看

![image](https://user-images.githubusercontent.com/38207492/103841272-20e07c80-50ce-11eb-8cb5-35b5184213b1.png)

**Comment by aaron52101314** [comment]
> JimureportServiceImpl 代码贴出来看看

@Component
class JimureportServiceImpl implements JmReportTokenServiceI {

    @Override
    public String getToken(HttpServletRequest request) {
        return ShiroUtils.getSessionId();
    }

    @Override
    public String getUsername(String token) {
        return ShiroUtils.getSysUser().getUserName();
    }

    @Override
    public Boolean verifyToken(String token) {
		return true;
        //return token.equals(ShiroUtils.getSessionId());
    }
}

**Comment by aaron52101314** [comment]
> JimureportServiceImpl 代码贴出来看看

    @PostMapping({ "/save" })
    @JimuLoginRequired
    public Result<?> a(final HttpServletRequest httpServletRequest, @RequestBody final JSONObject jsonObject) {
        try {
            return Result.OK((Object)this.jmReportDesignService.saveReport(jsonObject));
        }
        catch (Exception ex) {
            return Result.error(403, "token\u975e\u6cd5");
        }
    }

这里 return Result.error(403, "token\u975e\u6cd5");报错出来的!

**Comment by aaron52101314** [comment]
> > JimureportServiceImpl 代码贴出来看看
> 
> ```
> @PostMapping({ "/save" })
> @JimuLoginRequired
> public Result<?> a(final HttpServletRequest httpServletRequest, @RequestBody final JSONObject jsonObject) {
>     try {
>         return Result.OK((Object)this.jmReportDesignService.saveReport(jsonObject));
>     }
>     catch (Exception ex) {
>         return Result.error(403, "token\u975e\u6cd5");
>     }
> }
> ```
> 
> 这里 return Result.error(403, "token\u975e\u6cd5");报错出来的!

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.type.TypeException: 
Could not set parameters for mapping: 
ParameterMapping{property='ew.paramNameValuePairs.MPGENVAL1', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. 
Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . 
Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型

**Comment by zhangdaiscott** [comment]
配置错误
![image](https://user-images.githubusercontent.com/3162115/103841946-a7e22480-50cf-11eb-8ee1-025ae37eaf8c.png)

` //积木报表排除
        filterChainDefinitionMap.put("/jmreport/**", "anon");
        filterChainDefinitionMap.put("/**/*.js.map", "anon");
        filterChainDefinitionMap.put("/**/*.css.map", "anon");`

**Comment by aaron52101314** [comment]
> 配置错误
> ![image](https://user-images.githubusercontent.com/3162115/103841946-a7e22480-50cf-11eb-8ee1-025ae37eaf8c.png)
> 
> ```
> //积木报表排除
>         filterChainDefinitionMap.put("/jmreport/**", "anon");
>         filterChainDefinitionMap.put("/**/*.js.map", "anon");
>         filterChainDefinitionMap.put("/**/*.css.map", "anon");
> ```

啥东西哦？图片加载不出来，能否发一下？

**Comment by zhangdaiscott** [comment]
你用的什么数据库？

```
引入最新的试试
<dependency>
			<groupId>com.jimureport</groupId>
			<artifactId>spring-boot-starter-jimureport</artifactId>
			<version>1.1.03-beta</version>
		</dependency>
```

升级sql
```
ALTER TABLE `jimu_report_db`
ADD COLUMN `is_list` int(3) NULL DEFAULT 0 COMMENT '是否是列表0否1是 默认0' AFTER `api_method`;

update  jimu_report_db set is_list=1 where api_url like '%pageSize%' or is_page=1;
```

**Comment by aaron52101314** [comment]
> ALTER TABLE `jimu_report_db`
> ADD COLUMN `is_list` int(3) NULL DEFAULT 0 COMMENT '是否是列表0否1是 默认0' AFTER `api_method`;
> 
> update  jimu_report_db set is_list=1 where api_url like '%pageSize%' or is_page=1;


-->还是报错哦!
![image](https://user-images.githubusercontent.com/38207492/103864142-0a9de500-50fd-11eb-88aa-cd921855f11f.png)

![image](https://user-images.githubusercontent.com/38207492/103864005-cf031b00-50fc-11eb-9feb-c67e4d2a5c7b.png)
[](url)

[新建报表异常日志(oracle集成环境).txt](https://github.com/zhangdaiscott/JimuReport/files/5780146/oracle.txt)

**Comment by hupanfeng** [comment]
使用oracle数据库必然报这个错吴。其实是底层数据库访问已经报错了。但你们把异常信息丢了，然后还错误的提示token错误。也就是说到目前为止，你们宣称的支持oralce的只是个幌子。建议还是开放源代码吧，有问题大家一起修改。

**Comment by zhangdaiscott** [comment]
<dependency>
  <groupId>com.jimureport</groupId>
  <artifactId>spring-boot-starter-jimureport</artifactId>
  <version>1.1.04-beta</version>
</dependency>

**Comment by aaron52101314** [comment]
> ```
> <dependency>
>   <groupId>com.jimureport</groupId>
>   <artifactId>spring-boot-starter-jimureport</artifactId>
>   <version>1.1.04-beta</version>
> </dependency>
> ```

这个问题升级1.1.04-beta之后，是不报错了，但是点新建报表没反应啊，这就把issue关掉啦，这么草率么？？？？
