### ISSUE TITLE
分页查询有问题

### ISSUE THREAD

**Issue by hendidediaodiao** [zhangdaiscott/JimuReport#59]
数据集里面勾选了分页查询，但是浏览页面还是全部数据

**Comment by katriinatavi** [comment]
修改JmreportSqlUtils.class 的dbTypeIsMySQL,因为传过来的参数是MYSQL5.7但是判断是mysql,就不会进入mysql分页。
`public static boolean dbTypeIsMySQL(String dbType) {
        if (dbType.toLowerCase().contains("mysql")) {
            return true;
        } else {
            return false;
        }
    }`
这样就好了。

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
1.1.05版本已修复
