### ISSUE TITLE
字段太长,超出数据库字段的长度

### ISSUE THREAD

**Issue by zzwzqaa** [zhangdaiscott/JimuReport#60]
SELECT cct.furnace_number,
  vt.steel_grade,
  vt.model_type,
  vt.branch_count,
  vt.qu_xiang_1,
	al.all_count,
  cct.in_ear1,
  cct.mid1,
  cct.in_late1,
  cct.in_ear2,
  cct.mid2,
  cct.in_late2,
  cct.twenty_five_percent,
  cct.fifty_percent,
  cct.seventy_five_percent,
  cct.one_hundred_percent 
FROM
  continuous_casting_top cct
  INNER JOIN (
  SELECT
    cab.furnace_number,
    cab.casting_reservation,
    cab.team_group,
    ccc1.steel_grade,
    ( cab.grey_model1 || '*') || ccc1.LENGTH AS model_type,
    cab.grey_model1 AS grey_model_1,
    ccc1.LENGTH AS lenght_1,
    ccc1.branch_count,
    ccc1.qu_xiang AS qu_xiang_1, 
    ccc1.creation_time
  FROM
    continuous_casting_bottom cab
    LEFT JOIN continuous_casting_bottom_content1 ccb1 ON cab.ID = ccb1.continuous_casting_bottom_id
    LEFT JOIN continuous_casting_content ccc1 ON ccc1.ID = ccb1.content1_id 
    WHERE cab.casting_reservation LIKE '%${cr1}%' AND cab.team_group LIKE '%${tg1}%' AND ccc1.creation_time BETWEEN '${st1}' AND '${et1}'
  UNION ALL
  SELECT
    cab.furnace_number,
    cab.casting_reservation,
    cab.team_group,
    ccc2.steel_grade,
    ( cab.grey_model1 || '*' ) || ccc2.LENGTH AS model_type,
    cab.grey_model1 AS grey_model_1,
    ccc2.LENGTH AS lenght_1,
    ccc2.branch_count,
    ccc2.qu_xiang AS qu_xiang_1, 
    ccc2.creation_time
  FROM
    continuous_casting_bottom cab
    LEFT JOIN continuous_casting_bottom_content2 ccb2 ON cab.ID = ccb2.continuous_casting_bottom_id
    LEFT JOIN continuous_casting_content ccc2 ON ccc2.ID = ccb2.content2_id
    WHERE cab.casting_reservation LIKE '%${cr1}%' AND cab.team_group LIKE '%${tg1}%' AND ccc2.creation_time BETWEEN '${st1}' AND '${et1}'
  ) vt ON cct.furnace_number = vt.furnace_number 
	LEFT JOIN (
  SELECT
    vt_1.furnace_number,
    SUM ( vt_1.branch_count ) AS all_count 
  FROM
    (
    SELECT
      cab.furnace_number,
      ccc1.branch_count 
    FROM
      continuous_casting_bottom cab
      LEFT JOIN continuous_casting_bottom_content1 ccb1 ON cab.ID = ccb1.continuous_casting_bottom_id 
      LEFT JOIN continuous_casting_content ccc1 ON ccc1.ID = ccb1.content1_id 
			WHERE cab.casting_reservation LIKE '%${cr1}%' AND cab.team_group LIKE '%${tg1}%' AND ccc1.creation_time BETWEEN '${st1}' AND '${et1}'
		UNION ALL
    SELECT
      cab.furnace_number,
      ccc2.branch_count 
    FROM
      continuous_casting_bottom cab
      LEFT JOIN continuous_casting_bottom_content2 ccb2 ON cab.ID = ccb2.continuous_casting_bottom_id
      LEFT JOIN continuous_casting_content ccc2 ON ccc2.ID = ccb2.content2_id
			WHERE cab.casting_reservation LIKE '%${cr1}%' AND cab.team_group LIKE '%${tg1}%' AND ccc2.creation_time BETWEEN '${st1}' AND '${et1}'
    ) vt_1 
  GROUP BY
  vt_1.furnace_number 
  ) al ON al.furnace_number = cct.furnace_number

**Comment by zhangdaiscott** [comment]
报错截图发一下
