### ISSUE TITLE
API带查询条件时,每次访问页面会进行俩次接口调用

### ISSUE THREAD

**Issue by anAdventure** [zhangdaiscott/JimuReport#61]
比如编写Api loaclhost:8080/test?id='${id}'
访问报表传参 loaclhost:8080/test?id=1
方法会被请求俩次,第一次请求id参数为 '${id}'  第二次id参数值为 1

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
最新版1.1.05版本未重现，请提供详细代码和配置截图及测试步骤
