### ISSUE TITLE
int类型值为0的数据 无法展示

### ISSUE THREAD

**Issue by anAdventure** [zhangdaiscott/JimuReport#62]
{
"open_time": 19.5,
"close_time": 4.5,
"operation_time": 0,
"time1": 89.88,
"time2": 1.45,
"xn": 0,
"oee1": 0,
"oee2": 0
}
比如上面json oee1就无法在excel中展示

**Comment by zhangdaiscott** [comment]
显示效果是怎样的，空？

**Comment by tygithub1** [comment]
已修复 ，1.1.05版本
