### ISSUE TITLE
点击预览报错

### ISSUE THREAD

**Issue by 17564365445** [zhangdaiscott/JimuReport#64]
Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: VERSION_2_3_30

**Comment by zhangdaiscott** [comment]
freemarker版本低了

<dependency>
      <groupId>org.freemarker</groupId>
      <artifactId>freemarker</artifactId>
      <version>2.3.30</version>
      <scope>compile</scope>
    </dependency>
