### ISSUE TITLE
报表字段过多,浏览时候会显示不全

### ISSUE THREAD

**Issue by baoxituo1** [zhangdaiscott/JimuReport#65]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/8840719/104478039-c4fd8280-55fc-11eb-8912-da471d71a3d4.png)
![image](https://user-images.githubusercontent.com/8840719/104478098-d5adf880-55fc-11eb-82e4-6d753a27eda8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
已修复  1.1.05之后的版本会发布
