### ISSUE TITLE
指定了字典code之后，查询条件中有值，但查询结果中为空

### ISSUE THREAD

**Issue by africaadonis** [zhangdaiscott/JimuReport#66]
##### 版本号：
1.1.04-beta

##### 问题描述：
指定了字典code之后，查询条件中有值，但查询结果中为空

##### 截图&代码：
![QQ图片20210114120916](https://user-images.githubusercontent.com/40649464/104544159-168c2880-5662-11eb-98c6-b0f0f6604251.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
什么数据库？具体字段渲染咋配置的

**Comment by africaadonis** [comment]
现在好了，出现上述问题 是我升级<version>1.1.04-beta</version>后仍在<version>1.1.01</version>的报表上修改的，现在在<version>1.1.04-beta</version>版本上新建了一个新的报表，好了
