### ISSUE TITLE
一对多关系的报表可以实现吗

### ISSUE THREAD

**Issue by lizhaojian** [zhangdaiscott/JimuReport#67]
##### 版本号：
1.1.05

##### 问题描述：
一对多关系的报表可以实现吗,例如：一条入库记录对应多条出库记录

##### 截图&代码：
![image](https://user-images.githubusercontent.com/77473574/104677276-1e140600-5724-11eb-8213-3ff94cac536a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
目前不支持，收录，后期实现
