### ISSUE TITLE
非jeecgboot工程集成启动后，如何挂菜单；预览和查询结果不一致；日期格式化问题；输入法问题

### ISSUE THREAD

**Issue by africaadonis** [zhangdaiscott/JimuReport#68]
##### 版本号：
1.1.05

##### 问题描述：
1、非jeecgboot工程集成启动后，如何挂菜单，能给个思路或参考吗？
2、其他三个问题见下面截图
##### 截图&代码：
![image](https://user-images.githubusercontent.com/40649464/104711088-e0cb6a80-575b-11eb-9900-511b2683b93e.png)
![image](https://user-images.githubusercontent.com/40649464/104711124-ec1e9600-575b-11eb-95f4-48775866f236.png)
![image](https://user-images.githubusercontent.com/40649464/104711144-f2ad0d80-575b-11eb-9c04-aac85f296dc7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
菜单方式参考http://report.jeecg.com/2078875
