### ISSUE TITLE
excel导出问题

### ISSUE THREAD

**Issue by lizhaojian** [zhangdaiscott/JimuReport#69]
##### 版本号：
1.1.05

##### 问题描述：
数据可以显示出来但是导出excel文件的时候数据显示不出来,只显示表达式

##### 截图&代码：
![image](https://user-images.githubusercontent.com/77473574/104870331-346bcd00-5983-11eb-8dcf-3a79989e8e91.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这块还没改好，等下个版本，会做导出重构
