### ISSUE TITLE
无法打开报表设计器页面

### ISSUE THREAD

**Issue by learningpro** [zhangdaiscott/JimuReport#7]
按照readme的步骤，成功安装了依赖并给菜单设置了权限，点击“报表设计器”的时候，打开了新的标签页，提示
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Nov 01 11:33:52 CST 2020
There was an unexpected error (type=Not Found, status=404).
No message available

无法使用

**Comment by zhangdaiscott** [comment]
依赖没集成好

**Comment by zhangdaiscott** [comment]
备注： 如果你用的是微服务模式，需要自行配置gateway新路由。

**Comment by zhangdaiscott** [comment]
按照文档，添加好依赖并刷新依赖
https://my.oschina.net/jeecg/blog/4694834
