### ISSUE TITLE
数据报表打印-表头是否支持分页?

### ISSUE THREAD

**Issue by GitXiaoPing** [zhangdaiscott/JimuReport#70]
##### 问题描述：数据一多就需要分页打印，第一页有表头在还好，到其他页面就都是数据了，如果表头也能跟着分页，那样就舒服多了，就不用拿着第一张的表头对着看了。
效果图：
![image](https://user-images.githubusercontent.com/45633931/104883700-1d87a380-59a0-11eb-8477-6cdc2c94a842.png)

##### 截图&代码：
1.1.05 版本效果：
![image](https://user-images.githubusercontent.com/45633931/104883731-2aa49280-59a0-11eb-9d74-eb5d92248210.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
暂不支持

**Comment by GitXiaoPing** [comment]
后期会支持嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaiscott/JimuReport"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 晚上6:40
收件人:&nbsp;"zhangdaiscott/JimuReport"<JimuReport@noreply.github.com&gt;;
抄送:&nbsp;"wxp"<1809330247@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/JimuReport] 数据报表打印-表头是否支持分页? (#70)





 
暂不支持
