### ISSUE TITLE
PDF导出错误问题

### ISSUE THREAD

**Issue by areehy** [zhangdaiscott/JimuReport#72]
版本号：1.1.05

问题描述：excel导出正常 预览正常 pdf导出的时候有时数值不显示有时一直卡在加载界面

截图&代码：
![image](https://user-images.githubusercontent.com/14199405/105013233-fef5db00-5a79-11eb-9957-500088a0b450.png)
![image](https://user-images.githubusercontent.com/14199405/105013254-06b57f80-5a7a-11eb-99cc-9eaf4960f703.png)
![image](https://user-images.githubusercontent.com/14199405/105013283-0e752400-5a7a-11eb-85f1-280b77ac0639.png)
![image](https://user-images.githubusercontent.com/14199405/105013335-1b921300-5a7a-11eb-9c18-630aa2e01850.png)

**Comment by accpman** [comment]
已收录，待测试

**Comment by mini2014** [comment]
更新到最新版本
