### ISSUE TITLE
使用oracle数据库时，无法创建报表（进入新建报表页面前就报错）

### ISSUE THREAD

**Issue by hupanfeng** [zhangdaiscott/JimuReport#73]
##### 截图&代码：

1、使用的自定义数据源
2、表结构
CREATE TABLE "REPORT_TEST"."JIMU_REPORT" (
  "ID" NVARCHAR2(32) VISIBLE NOT NULL,
  "CODE" NVARCHAR2(50) VISIBLE,
  "NAME" NVARCHAR2(50) VISIBLE,
  "NOTE" NVARCHAR2(255) VISIBLE,
  "STATUS" NVARCHAR2(10) VISIBLE,
  "TYPE" NVARCHAR2(10) VISIBLE,
  "JSON_STR" NCLOB VISIBLE,
  "API_URL" NVARCHAR2(255) VISIBLE,
  "THUMB" NCLOB VISIBLE,
  "CREATE_BY" NVARCHAR2(50) VISIBLE,
  "CREATE_TIME" DATE VISIBLE,
  "UPDATE_BY" NVARCHAR2(50) VISIBLE,
  "UPDATE_TIME" DATE VISIBLE,
  "DEL_FLAG" NUMBER(4,0) VISIBLE,
  "API_METHOD" NVARCHAR2(255) VISIBLE,
  "API_CODE" NVARCHAR2(255) VISIBLE,
  "TEMPLATE" NUMBER(4,0) VISIBLE,
  "VIEW_COUNT" NUMBER(20,0) VISIBLE
)
3、报错sql
SELECT id,code,name,note,status,type,json_str,api_url,api_method,api_code,thumb,template,create_by,create_time,update_by,update_time,del_flag,view_count FROM jimu_report WHERE (id = ?)
4、错误信息：
2021-01-20 15:53:46.625 ERROR 5761 --- [nio-8085-exec-8] o.jeecg.modules.jmreport.desreport.a.a   : nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='ew.paramNameValuePairs.MPGENVAL1', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='ew.paramNameValuePairs.MPGENVAL1', mode=IN, javaType=class java.lang.Object, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
脚本你怎么转的？

**Comment by hupanfeng** [comment]
用navicat从mysql转的

**Comment by zhangdaiscott** [comment]
我们联调的是oracle11g，你用这个版本试试

```
<dependency>
  <groupId>com.jimureport</groupId>
  <artifactId>spring-boot-starter-jimureport</artifactId>
  <version>1.1.06</version>
</dependency>
```

**Comment by hupanfeng** [comment]
问题出在这里： 没有判断excelConfigId是否为空
if (StringUtils.isNotEmpty(excelConfigId)) {
            LambdaQueryWrapper<JimuReport> lambdaQueryWrapper = new LambdaQueryWrapper();
            lambdaQueryWrapper.eq(JimuReport::getId, excelConfigId);
            jimuReport = this.baseMapper.selectOne(lambdaQueryWrapper);
        }

**Comment by zhangdaiscott** [comment]
那个类，哪行代码，发issue请详细

**Comment by zhangdaiscott** [comment]
收录

**Comment by tygithub1** [comment]
此问题新版代码已经修复
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.2.0</version>
</dependency>
