### ISSUE TITLE
Oracle19c 查询出错

### ISSUE THREAD

**Issue by cai115le** [zhangdaiscott/JimuReport#74]
##### 版本号：
1.1.05

##### 问题描述：
使用oracle19c时，sql解析正常，预览数据的时候报错，日志显示为查询总条数错误

##### 截图&代码：

原始sql：
![image](https://user-images.githubusercontent.com/18572884/105316929-879c8480-5bfc-11eb-8bc5-9b78a96ea6eb.png)

SELECT
	( CASE WHEN ITF.CUST_ID IS NULL THEN FTI.CUST_ID ELSE ITF.CUST_ID END ) CUST_ID,
	( CASE WHEN ITF.CUST_ID IS NULL THEN FTI.CUST_NAME ELSE ITF.CUST_NAME END ) CUST_NAME,
	ITF.ITF_ACRT,
	ITF.ITF_UCRT,
	FTI.FIT_ACRT,
	FTI.FIT_UCRT 
FROM …
日志显示sql，多了 “* from ECT” 
![image](https://user-images.githubusercontent.com/18572884/105316992-9e42db80-5bfc-11eb-930f-79a40fb8cbd3.png)
select * from (select * from ECT
	( CASE WHEN ITF.CUST_ID IS NULL THEN FTI.CUST_ID ELSE ITF.CUST_ID END ) CUST_ID,
	( CASE WHEN ITF.CUST_ID IS NULL THEN FTI.CUST_NAME ELSE ITF.CUST_NAME END ) CUST_NAME,
	ITF.ITF_ACRT,
	ITF.ITF_UCRT,
	FTI.FIT_ACRT,
	FTI.FIT_UCRT 
FROM ...

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
已收录，待测试后反馈

**Comment by 1298191366** [comment]
请更新到最新版再次尝试
