### ISSUE TITLE
积木报表套打问题

### ISSUE THREAD

**Issue by chenshan07073311** [zhangdaiscott/JimuReport#77]
##### 问题描述：
1、报表设计的时候没有留白，打印的时候留白好多，实际打印缩小了很多

 2、切换为横向之后 纵向切换不回去了 选项都没有了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/27768927/105673618-415b6400-5f21-11eb-8389-09d4a71b7ad1.png)

![image](https://user-images.githubusercontent.com/27768927/105673673-5801bb00-5f21-11eb-8684-bdee9c290302.png)

![image](https://user-images.githubusercontent.com/27768927/105673750-78317a00-5f21-11eb-9f62-39d4efda5b57.png)

![image](https://user-images.githubusercontent.com/27768927/105674091-f5f58580-5f21-11eb-8f97-20b01a9545f8.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
已收录

**Comment by tygithub1** [comment]
无套打图片走的是普通打印

**Comment by chenshan07073311** [comment]
![image](https://user-images.githubusercontent.com/27768927/106691770-0b983880-660f-11eb-99ff-48d4bccb0b52.png)
http://report.jeecg.com/2084140  这里讲的是支持套打

**Comment by tygithub1** [comment]
那不得按步骤走吗？

**Comment by chenshan07073311** [comment]
是按照步骤走的 有问题

**Comment by chenshan07073311** [comment]
设计的表格满屏的 打印缩小了   这个功能你们调试过吗？  边距我都设置为0的

**Comment by tygithub1** [comment]
套打边距代码写死了0 不需要人为设置 有例子好说话，不然扯一天都能不明白

**Comment by chenshan07073311** [comment]
http://www.jimureport.com/login  15158176442

**Comment by chenshan07073311** [comment]
你用我的账号登录  验证码待会发你

**Comment by chenshan07073311** [comment]
打我电话 或者加我微信都可以

**Comment by tygithub1** [comment]
已找到例子

**Comment by chenshan07073311** [comment]
打印出来的表格比实际匹配的图稍微大一点  你那边问题修复的时候 用的背景图片  宽高分别是多少的

**Comment by chenshan07073311** [comment]
方便留个QQ吗  不知道您是群里的哪位

**Comment by chenshan07073311** [comment]
我的 847657631

**Comment by chenshan07073311** [comment]
![image](https://user-images.githubusercontent.com/27768927/108687146-5089fd80-7531-11eb-9420-5e3b1c7b6a59.png)
![image](https://user-images.githubusercontent.com/27768927/108687161-57187500-7531-11eb-9b5a-fed4a9bc9a63.png)
上面是画的表格 下面是打印出来的表格 打印的比画出来的表格要大一点

**Comment by tygithub1** [comment]
https://www.kancloud.cn/zhangdaiscott/jimureport/2141759
