### ISSUE TITLE
关于二维码一维码动态生成

### ISSUE THREAD

**Issue by coolxiaohao** [zhangdaiscott/JimuReport#78]
##### 版本号：
v1.1.05

##### 问题描述：
@zhangdaiscott 
二维码一维码无法动态设置值，期待后续有所更新，另外对sqlserver的支持也期待进一步优化

##### 截图&代码：
![image](https://user-images.githubusercontent.com/46562305/105687443-6b1d8680-5f33-11eb-969a-839d2d6241eb.png)

**Comment by mini2014** [comment]
正在优化，下个版本支持！

**Comment by mini2014** [comment]
最新版本支持了
