### ISSUE TITLE
套打预览打印后，对不齐

### ISSUE THREAD

**Issue by spar025** [zhangdaiscott/JimuReport#8]
操作步骤：
1、点开报表设计器
2、新建报表，导入图片并设置为套打图片
3、调整单元格，与图片填写内容处对齐，输入内容
4、保存并填写报表名称，#bug1
5、调整后再次保存，点击预览，看到套打图片与内容吻合
6、为了保证图片与实际大小相符，进行如下操作：1、第一次打印直接打印图片，再将打印出的图片放入打印机；2、点击设计器预览中的打印按钮。#bug2

bug说明：
bug1：第一次保存报表，调整好的位置会在保存后刷新时改变位置，需要微调。
bug2：打印出来的套打，对不齐，内容列在实际打印出来都会偏左一列，与图片重合了。请参考效果图。

bug1效果图：
第一次保存前调整好后的截图：
![11](https://user-images.githubusercontent.com/33474854/97934572-10034a00-1db1-11eb-9c6a-76683bcb31fc.jpg)
第一次保存自动刷新页面后的截图，一定程度的向右偏和向下偏：
![保存后](https://user-images.githubusercontent.com/33474854/97934574-11347700-1db1-11eb-91da-50fdc56a6e28.jpg)
bug2效果图：
![打印错误结果](https://user-images.githubusercontent.com/33474854/97933921-155f9500-1daf-11eb-8172-6cb13b2941ca.jpg)

**Comment by zhangdaiscott** [comment]
感谢反馈，我们看看

**Comment by tygithub1** [comment]
已修复
