### ISSUE TITLE
数字只显示整数，小数被四舍五入了

### ISSUE THREAD

**Issue by seenukwan** [zhangdaiscott/JimuReport#81]

**Comment by seenukwan** [comment]
> ##### 版本号：1.1.09-beta
> ##### 问题描述：更新到1.1.09后，接口返回数据带小数，但是页面显示成四舍五入保留整数，修改数据格式，单元格格式都没办法正常显示正确数值，1.1.05版本是没问题的，麻烦查看一下
> ##### 截图&代码：

查了一下是字符类型的问题，bigDecimal和double都有这个问题，讲对象的类型改成String可以正常显示小数，麻烦修复一下这个bug

**Comment by mini2014** [comment]
已收录

**Comment by tygithub1** [comment]
已修复 下个版本1.1.05++ 发布
