### ISSUE TITLE
使用postgresql 数据库存储报表数据bug

### ISSUE THREAD

**Issue by huanfion** [zhangdaiscott/JimuReport#82]
##### 版本号：

1.1.09-beta
##### 问题描述：
把mysql 通过Navicat工具转成postgresql，编辑报表保存时报错。

### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: column "is_list" is of type integer but expression is of type character varying↵  建议：You will need to rewrite or cast the expression.↵  位置：232
↵### The error may exist in org/jeecg/modules/jmreport/desreport/mapper/JmReportDbMapper.java (best guess)
↵### The error may involve org.jeecg.modules.jmreport.desreport.mapper.JmReportDbMapper.insert-Inline
↵### The error occurred while setting parameters
↵### SQL: INSERT INTO jimu_report_db  ( id, jimu_report_id, db_code, db_ch_name, db_type,  db_dyn_sql,        is_page, is_list, db_source, db_source_type, create_by,  create_time, update_time )  VALUES  ( ?, ?, ?, ?, ?,  ?,        ?, ?, ?, ?, ?,  ?, ? )
↵### Cause: org.postgresql.util.PSQLException: ERROR: column "is_list" is of type integer but expression is of type character varying↵  建议：You will need to rewrite or cast the expression.↵  位置：232↵; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "is_list" is of type integer but expression is of type character varying↵  建议：You will need to rewrite or cast the expression.↵  位置：232"

![image](https://user-images.githubusercontent.com/8652475/105819242-e5f9a680-5ff2-11eb-9f99-a8fd60000554.png)
postgresql 对应的jimu_report_db 表结构如下图
![image](https://user-images.githubusercontent.com/8652475/105819974-e21a5400-5ff3-11eb-920c-53620cfd1b4f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
已收录

**Comment by 1298191366** [comment]
![image](https://user-images.githubusercontent.com/30997828/106420534-d3211f00-6495-11eb-98ef-84898ebb8373.png)
这个是我转到，可以运行，不报错，我对比了一下是isList字段，你把他改成varchar再次尝试
