### ISSUE TITLE
支持图表间的数据联动吗

### ISSUE THREAD

**Issue by tjthink** [zhangdaiscott/JimuReport#84]
##### 版本号：
1.1.05

##### 问题描述：
支持图表间的数据联动吗，A\B两个图表，点击A，然后B图表的数据根据A来变化

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
暂不支持！

**Comment by zhangdaiscott** [comment]
暂时不好实现，先归集到
https://github.com/zhangdaiscott/JimuReport/issues/138
