### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by zhangyaotian1978** [zhangdaiscott/JimuReport#85]
##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。
![QQ图片20210128113212](https://user-images.githubusercontent.com/44627607/106086130-84ede200-615c-11eb-96c9-4c12202479e3.png)

**Comment by zhangdaiscott** [comment]
收录

**Comment by accpman** [comment]
已修复，下个版本更新
