### ISSUE TITLE
Api数据集解析后台提示token为空

### ISSUE THREAD

**Issue by qsh106** [zhangdaiscott/JimuReport#86]
##### 版本号：
积木报表1.1.05，jeecg-boot 2.4

##### 问题描述：
设计积木报表时使用Api数据集，解析Api地址“http://localhost:8080/jeecg-boot/ryJbqk/ryJbqk/list”时后台报“token为空“错误。这个问题如何解决？

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/48463491/106269911-2150db00-6268-11eb-8667-964de534f891.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录，看看是否传递了jeecgboot默认token head

**Comment by lsqGitHub716** [comment]
解析的时候请求头里有token的信息吗

**Comment by qsh106** [comment]
发自我的华为手机有信息头，如果没有头都不能打开-------- 原始邮件 --------主题：Re: [zhangdaiscott/JimuReport] Api数据集解析后台提示token为空 (#86)发件人：lsqGitHub716 收件人：zhangdaiscott/JimuReport 抄送：qsh106 ,Author 

解析的时候请求头里有token的信息吗

**Comment by lsqGitHub716** [comment]
把你的请求头信息，报错信息贴一下

**Comment by qsh106** [comment]
我升级到2.4.2了，今天回到2.4看一下发现启动不了了等我再次启动后把情况截图出来，升级1.1.09后问题消失了。发自我的华为手机-------- 原始邮件 --------主题：Re: [zhangdaiscott/JimuReport] Api数据集解析后台提示token为空 (#86)发件人：lsqGitHub716 收件人：zhangdaiscott/JimuReport 抄送：qsh106 ,Author 

把你的请求头信息，报错信息贴一下

**Comment by qsh106** [comment]
![Uploading IMG_20210209_085652.jpg…]()

**Comment by qsh106** [comment]
![IMG_20210209_085714](https://user-images.githubusercontent.com/48463491/107301671-d3ac4d80-6a73-11eb-873f-d694bdd334ba.jpg)
![1612758227996](https://user-images.githubusercontent.com/48463491/107301675-d5761100-6a73-11eb-83d5-9888103dfe30.jpg)

**Comment by zhangdaiscott** [comment]
jimureport升级到1.1.09

```
<dependency>
  <groupId>com.jimureport</groupId>
  <artifactId>spring-boot-starter-jimureport</artifactId>
  <version>1.1.09</version>
</dependency>
```
