### ISSUE TITLE
jeecgboot2.2集成jimureport报错

### ISSUE THREAD

**Issue by helloRewen** [zhangdaiscott/JimuReport#87]
##### 版本号：
jeecgboot2.2

##### 问题描述：
集成jimureport，启动后，点击菜单报400错误，后台报“ The valid characters are defined in RFC 7230 and RFC 3986”

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49238216/106375996-fe3f3c00-63cb-11eb-9d27-6098c916fc11.png)
![image](https://user-images.githubusercontent.com/49238216/106375999-04351d00-63cc-11eb-96d2-f106c9dc1b3e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
仔细看这个文档，http://report.jeecg.com/2078875  你这个错没遇到过
