### ISSUE TITLE
数据内容支持html标签吗

### ISSUE THREAD

**Issue by lchen1388** [zhangdaiscott/JimuReport#88]
##### 版本号：
1.1.09-beta

##### 问题描述：
数据内容是否支持html标签，或有什么方式实现吗

##### 截图&代码：
![1](https://user-images.githubusercontent.com/29558671/106547427-28b60400-6548-11eb-8592-d3c79086ae22.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
暂不支持

**Comment by zhangdaiscott** [comment]
暂时不好实现，先归集到
https://github.com/zhangdaiscott/JimuReport/issues/138
