### ISSUE TITLE
mysql数据源连接错误

### ISSUE THREAD

**Issue by tancw** [zhangdaiscott/JimuReport#89]
##### 问题描述：mysql数据源连接错误
远程连接数据库报错
数据源地址   jdbc:mysql://192.168.1.172:3306/junsi_fee
数据库版本  5.7.28

##### 截图&代码：
Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server
![QQ图片20210202143312](https://user-images.githubusercontent.com/28651840/106561606-f914f500-6563-11eb-8295-de93860a4c63.png)

**Comment by 1298191366** [comment]
经测试可以连接成功，局域网本地可以连接，但是线上不能连接局域网的,我这里就是连接就是远程数据库
![image](https://user-images.githubusercontent.com/30997828/106713495-82e0c300-6635-11eb-84fa-efb7c660d24a.png)

**Comment by 1298191366** [comment]
可以尝试新版本在测试一下，现在版本是1.1.09-beta

**Comment by tancw** [comment]
> 经测试可以连接成功，局域网本地可以连接，但是线上不能连接局域网的,我这里就是连接就是远程数据库
> ![image](https://user-images.githubusercontent.com/30997828/106713495-82e0c300-6635-11eb-84fa-efb7c660d24a.png)

那我是要部署离线版本才能远程连接？

**Comment by 1298191366** [comment]
你说的远程连接是线上连接你本地数据库还是线上数据库，如果需要连接本地数据库，只能下载离线版，用本地连接

**Comment by tancw** [comment]
> 你说的远程连接是线上连接你本地数据库还是线上数据库，如果需要连接本地数据库，只能下载离线版，用本地连接

数据库在另一台服务器上

**Comment by zhangdaiscott** [comment]
外网通吗，自己先确认下非程序下，是否能链接成功
