### ISSUE TITLE
集成后，访问报错了

### ISSUE THREAD

**Issue by yanyanpeng** [zhangdaiscott/JimuReport#9]
![image](https://user-images.githubusercontent.com/60538506/97968281-67c5a380-1df9-11eb-94c7-b02a0de3263f.png)

**Comment by zhangdaiscott** [comment]
描述过于简单

**Comment by zhangdaiscott** [comment]
按照文档配置下shiro排除
https://my.oschina.net/jeecg/blog/4694834
