### ISSUE TITLE
【feature】token的处置上增加灵活性

### ISSUE THREAD

**Issue by tour1986** [zhangdaiscott/JimuReport#91]
##### 版本号：
1.1.09-beta

##### 问题描述：
针对非jeecg平台的集成，token的处置上，希望能更灵活一些。

##### 截图&代码：
当前版本是将传入的token放入“X-Access-Token”
![image](https://user-images.githubusercontent.com/6590665/106729268-41a5de80-6648-11eb-973a-9e7e97d8ae78.png)
但是各平台对于token的参数可能采用“Authorization: Bearer”形式

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
已收录

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2132542

**Comment by pkaq** [comment]
我们系统就是放在Authorization里面的
