### ISSUE TITLE
选择全部打印时，打印数据条数收到1000条限制

### ISSUE THREAD

**Issue by he0128** [zhangdaiscott/JimuReport#92]
##### 问题描述：
打印数据条数在1W条以上，收到只能打印1000条数据的限制，希望能打印更多是条数据

##### 截图&代码：

![image](https://user-images.githubusercontent.com/52776371/106859637-4af18280-66fe-11eb-81be-a93f30dae782.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
此版本已经解决
```
<dependency> 
<groupId>com.jimureport</groupId> 
<artifactId>spring-boot-starter-jimureport</artifactId> 
<version>1.2.0-beta</version> 
</dependency>
```
