### ISSUE TITLE
无法根据查询条件打印

### ISSUE THREAD

**Issue by he0128** [zhangdaiscott/JimuReport#93]
##### 问题描述：
我根据查询条件 查询出来的数据 点击“全部打印” 打印出来的还是提示我数据不能超出1000条

##### 截图&代码：
![1612426664066](https://user-images.githubusercontent.com/52776371/106864242-8db65900-6704-11eb-904d-20865f7bebb1.jpg)

![C31895CC48D77C06587F6E76FD8D0736](https://user-images.githubusercontent.com/52776371/106864079-5f387e00-6704-11eb-8dbe-95700efdd9d3.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mini2014** [comment]
已修复！

引入jar
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>spring-boot-starter-jimureport</artifactId>
  <version>1.2.0</version>
</dependency>
