### ISSUE TITLE
1.1.09版本无法导出Excel

### ISSUE THREAD

**Issue by mengxiancai** [zhangdaiscott/JimuReport#94]
##### 版本号：
1.1.09

##### 问题描述：
无法导出Excel

##### 截图&代码：
![1](https://user-images.githubusercontent.com/33414416/106981503-12ed4c80-679d-11eb-9bf1-77f099d16cc5.png)
![2](https://user-images.githubusercontent.com/33414416/106981505-1385e300-679d-11eb-848c-62b4e818f8f1.png)
![3](https://user-images.githubusercontent.com/33414416/106981509-14b71000-679d-11eb-9d74-3f29c326e55c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请删除本地仓库依赖，重新下载，已经修复了上传maven仓库
