### ISSUE TITLE
api数据集并发获取

### ISSUE THREAD

**Issue by trek600** [zhangdaiscott/JimuReport#95]
##### 问题描述：
现在制作的报表的数据源来自多个表和库,使用sql数据源不太现实.因此使用api的方式后台聚合数据整理结果集.
但报表需要多个api数据集,数据集的数量比较多,大概几个到十几个,需要显示到不同的区域.但是现在报表的显示时间太长,想要加速显示,一方面我们提升接口性能,另一方面想问下多个数据集能都并发获取,这样可以加速获取全量的数据集,渲染的速度应该会加快.

**Comment by zhangdaiscott** [comment]
收录，我们考虑下
不过并发获取可会存在问题，如果其中一个有问题，会导致整体延迟

**Comment by zhangdaiscott** [comment]
暂时不好实现，先归集到
https://github.com/zhangdaiscott/JimuReport/issues/138
