### ISSUE TITLE
可否增加打印清晰度默认值的设定

### ISSUE THREAD

**Issue by wskqqw** [zhangdaiscott/JimuReport#96]
版本号：1.1.09
问题描述：
           需频繁打印的使用场景，打印清晰度默认值为0，打出来有些模糊，不大清晰，每次都得手动调整，容易出现打印出来拿到手才想起清晰度忘记调整。可否增加打印清晰度默认值调整的功能？
 截图&代码：
![image](https://user-images.githubusercontent.com/48768539/106997091-388a4e00-67bd-11eb-9c28-70f52e55fada.png)

**Comment by zhangdaiscott** [comment]
已经规划，下个版本应该可以

**Comment by zhangdaiscott** [comment]
已经支持请更新依赖
http://report.jeecg.com/2200803
```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>spring-boot-starter-jimureport</artifactId>
    <version>1.3.0-beta</version>
</dependency>
```
