### ISSUE TITLE
打印绿线无法拖动

### ISSUE THREAD

**Issue by anAdventure** [zhangdaiscott/JimuReport#97]
##### 版本号：

1.1.09
##### 问题描述：
打印绿线无法拖动
##### 截图&代码：

![11](https://user-images.githubusercontent.com/53201073/107013440-4cda4500-67d5-11eb-9402-e1e2712a6e25.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by pz1026** [comment]
遇到相同问题，请问如何解决？

**Comment by zhangdaiscott** [comment]
现在规则改了，不让改了，可以参考这个设置
http://report.jeecg.com/2084081
