### ISSUE TITLE
和minio发送冲突

### ISSUE THREAD

**Issue by anAdventure** [zhangdaiscott/JimuReport#98]
##### 版本号：
1.1.09

##### 问题描述：
jeecgboot更新1.1.09后，minio报错

##### 截图&代码：
正常整合minio和积木报表没有问题,但是使用jeecg框架整合1.1.09这个版本会报错

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by accpman** [comment]
jeecg框架那个版本，贴出错误信息

**Comment by anAdventure** [comment]
![Uploading image.png…]()

**Comment by anAdventure** [comment]
![image](https://user-images.githubusercontent.com/53201073/109372696-e1702880-78e5-11eb-9e56-d65a952974fe.png)

**Comment by zhangdaiscott** [comment]
http://cloud.jeecg.com/page?id=1351098016089526273
