### ISSUE TITLE
打印全部：无法打印，带参查询出来的数据

### ISSUE THREAD

**Issue by 13071652014** [zhangdaiscott/JimuReport#99]
##### 版本号：
1.1.09

##### 问题描述：
报表打印的 打印全部功能无法带参打印

##### 截图&代码：
官方实例，默认参数 id =1
![图片](https://user-images.githubusercontent.com/56342460/108472200-65fbef00-72c7-11eb-98a1-231a87dae68f.png)
将参数 id 改成 2 时，打印全部，打印出来的仍然是默认值 id = 1 的数据
![图片](https://user-images.githubusercontent.com/56342460/108472384-a22f4f80-72c7-11eb-8425-497f30548dd3.png)
![图片](https://user-images.githubusercontent.com/56342460/108472549-dc005600-72c7-11eb-93d4-219177515e51.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录

**Comment by mini2014** [comment]
**经测试没有问题**
如果你使用的是我们模板的例子，切换肯定数据不变，因为线上API没配置id参数；

**建议：**
1、自己做个SQL数据集例子，测试一下；
2、自己写个API例子，注意配置上查询参数，测试一下；
